CREATE EXTENSION IF NOT EXISTS POSTGIS;

CREATE SCHEMA BUSLANES;
SET SEARCH_PATH = BUSLANES, PUBLIC;

CREATE TABLE BUSLANES.CITIES
(
    ID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCE_INDEX    INTEGER UNIQUE,
    SLUG            TEXT             NOT NULL UNIQUE,
    NAME            TEXT             NOT NULL UNIQUE,
    FULL_NAME       TEXT,
    POPULATION      INTEGER          NOT NULL CHECK (POPULATION > 0),
    LANE_LENGTH_M   DOUBLE PRECISION NOT NULL CHECK (LANE_LENGTH_M >= 0),
    LANE_M_PER_1000 DOUBLE PRECISION GENERATED ALWAYS AS ( LANE_LENGTH_M / POPULATION * 1000.0 ) STORED,
    IS_LARGE        BOOLEAN GENERATED ALWAYS AS (POPULATION > 400000) STORED,
    BOUNDS          BOX2D            NOT NULL,
    ATTRIBUTES      JSONB            NOT NULL DEFAULT '{}'::JSONB,
    CREATED_AT      TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

CREATE TABLE BUSLANES.CITY_GEOMETRIES
(
    ID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CITY_ID       BIGINT                   NOT NULL REFERENCES CITIES (ID) ON DELETE CASCADE,
    LANES         SMALLINT                 NOT NULL CHECK (LANES > 0),
    LENGTH_M      DOUBLE PRECISION         NOT NULL CHECK (LENGTH_M >= 0),
    LANE_LENGTH_M DOUBLE PRECISION         NOT NULL CHECK (LANE_LENGTH_M >= 0),
    PROPERTIES    JSONB                    NOT NULL DEFAULT '{}'::JSONB,
    GEOM          GEOMETRY(Geometry, 4326) NOT NULL,
    CREATED_AT    TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    CONSTRAINT CITY_GEOMETRIES_LINEAR CHECK ( GEOMETRYTYPE(GEOM) IN ('LINESTRING', 'MULTILINESTRING') ),
    CONSTRAINT CITY_GEOMETRIES_VALID CHECK (ST_ISVALID(GEOM))
);
CREATE INDEX CITIES_RANKING_IDX ON CITIES (IS_LARGE DESC, LANE_M_PER_1000 DESC, NAME);
CREATE INDEX CITY_GEOMETRIES_CITY_ID_IDX ON CITY_GEOMETRIES (CITY_ID);
CREATE INDEX CITY_GEOMETRIES_GEOM_GIST_IDX ON CITY_GEOMETRIES USING GIST (GEOM);
COMMENT ON TABLE CITIES IS 'City attributes and cached viewport bounds used by the ranking and map.';
COMMENT ON TABLE CITY_GEOMETRIES IS 'PostGIS line geometries for bus lanes, linked to exactly one city.';
COMMENT ON COLUMN CITIES.LANE_LENGTH_M IS 'Lane-aware total in metres; a two-direction lane is counted twice.';
COMMENT ON COLUMN CITY_GEOMETRIES.PROPERTIES IS 'Source GeoJSON properties retained for lossless API output.';
