SET SEARCH_PATH = BUSLANES, PUBLIC;

CREATE TABLE IF NOT EXISTS BUSLANES.CITY_POPULATIONS
(
    CITY_ID     BIGINT      PRIMARY KEY REFERENCES BUSLANES.CITIES (ID) ON DELETE CASCADE,
    POPULATION  INTEGER     NOT NULL CHECK (POPULATION > 0),
    AS_OF       DATE,
    SOURCE      TEXT,
    ATTRIBUTES  JSONB       NOT NULL DEFAULT '{}'::JSONB,
    CREATED_AT  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $MIGRATION$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'buslanes'
          AND TABLE_NAME = 'cities'
          AND COLUMN_NAME = 'population'
    ) THEN
        EXECUTE $SQL$
            INSERT INTO BUSLANES.CITY_POPULATIONS (CITY_ID, POPULATION)
            SELECT ID, POPULATION
            FROM BUSLANES.CITIES
            ON CONFLICT (CITY_ID) DO NOTHING
        $SQL$;
    END IF;
END
$MIGRATION$;

DROP INDEX IF EXISTS BUSLANES.CITIES_RANKING_IDX;

ALTER TABLE BUSLANES.CITIES
    DROP COLUMN IF EXISTS LANE_M_PER_1000,
    DROP COLUMN IF EXISTS IS_LARGE,
    DROP COLUMN IF EXISTS POPULATION;

ALTER TABLE BUSLANES.CITIES
    ADD COLUMN IF NOT EXISTS LANE_M_PER_1000 DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS IS_LARGE BOOLEAN;

DO $MIGRATION$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM PG_CONSTRAINT
        WHERE CONRELID = 'BUSLANES.CITY_GEOMETRIES'::REGCLASS
          AND CONNAME = 'city_geometries_direction_multiplier'
    ) THEN
        ALTER TABLE BUSLANES.CITY_GEOMETRIES
            ADD CONSTRAINT CITY_GEOMETRIES_DIRECTION_MULTIPLIER
                CHECK (LANES IN (1, 2));
    END IF;
END
$MIGRATION$;

UPDATE BUSLANES.CITY_GEOMETRIES
SET LENGTH_M = ST_LENGTH(GEOM::GEOGRAPHY),
    LANE_LENGTH_M = ST_LENGTH(GEOM::GEOGRAPHY) * LANES;

WITH GEOMETRY_STATISTICS AS (
    SELECT CITY_ID,
           SUM(LANE_LENGTH_M)::DOUBLE PRECISION AS LANE_LENGTH_M,
           ST_EXTENT(GEOM)::BOX2D AS BOUNDS
    FROM BUSLANES.CITY_GEOMETRIES
    GROUP BY CITY_ID
),
CITY_STATISTICS AS (
    SELECT CITY.ID AS CITY_ID,
           COALESCE(GEOMETRY.LANE_LENGTH_M, 0) AS LANE_LENGTH_M,
           COALESCE(GEOMETRY.BOUNDS, CITY.BOUNDS) AS BOUNDS,
           POPULATION.POPULATION
    FROM BUSLANES.CITIES AS CITY
    LEFT JOIN GEOMETRY_STATISTICS AS GEOMETRY
      ON GEOMETRY.CITY_ID = CITY.ID
    LEFT JOIN BUSLANES.CITY_POPULATIONS AS POPULATION
      ON POPULATION.CITY_ID = CITY.ID
)
UPDATE BUSLANES.CITIES AS CITY
SET LANE_LENGTH_M = STATISTICS.LANE_LENGTH_M,
    BOUNDS = STATISTICS.BOUNDS,
    LANE_M_PER_1000 = CASE
        WHEN STATISTICS.POPULATION IS NULL THEN NULL
        ELSE STATISTICS.LANE_LENGTH_M / STATISTICS.POPULATION * 1000.0
    END,
    IS_LARGE = CASE
        WHEN STATISTICS.POPULATION IS NULL THEN NULL
        ELSE STATISTICS.POPULATION > 400000
    END,
    UPDATED_AT = NOW()
FROM CITY_STATISTICS AS STATISTICS
WHERE CITY.ID = STATISTICS.CITY_ID;

CREATE INDEX IF NOT EXISTS CITIES_RANKING_IDX
    ON BUSLANES.CITIES (
        IS_LARGE DESC NULLS LAST,
        LANE_M_PER_1000 DESC NULLS LAST,
        NAME
    );

COMMENT ON TABLE BUSLANES.CITY_POPULATIONS IS
    'Current population snapshot, maintained independently from bus-lane geometry.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.LANES IS
    'Direction multiplier: 1 for one-way and 2 for two-way bus lanes.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.LENGTH_M IS
    'Geodesic WGS84 length in metres, calculated with ST_Length(geom::geography).';
