SET SEARCH_PATH = BUSLANES, PUBLIC;

CREATE TABLE IF NOT EXISTS BUSLANES.CITY_MATCH_BOUNDS
(
    CITY_ID     BIGINT PRIMARY KEY REFERENCES BUSLANES.CITIES (ID) ON DELETE CASCADE,
    BOUNDS      PUBLIC.GEOMETRY(Polygon, 4326) NOT NULL,
    PRIORITY    INTEGER NOT NULL DEFAULT 0,
    ENABLED     BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT CITY_MATCH_BOUNDS_VALID CHECK (ST_ISVALID(BOUNDS))
);

INSERT INTO BUSLANES.CITY_MATCH_BOUNDS (CITY_ID, BOUNDS)
SELECT ID,
       ST_MAKEENVELOPE(
           ST_XMIN(BOUNDS) - CASE
               WHEN ST_XMIN(BOUNDS) = ST_XMAX(BOUNDS) THEN 0.000001
               ELSE 0
           END,
           ST_YMIN(BOUNDS) - CASE
               WHEN ST_YMIN(BOUNDS) = ST_YMAX(BOUNDS) THEN 0.000001
               ELSE 0
           END,
           ST_XMAX(BOUNDS) + CASE
               WHEN ST_XMIN(BOUNDS) = ST_XMAX(BOUNDS) THEN 0.000001
               ELSE 0
           END,
           ST_YMAX(BOUNDS) + CASE
               WHEN ST_YMIN(BOUNDS) = ST_YMAX(BOUNDS) THEN 0.000001
               ELSE 0
           END,
           4326
       )
FROM BUSLANES.CITIES
ON CONFLICT (CITY_ID) DO NOTHING;

CREATE INDEX IF NOT EXISTS CITY_MATCH_BOUNDS_GIST_IDX
    ON BUSLANES.CITY_MATCH_BOUNDS USING GIST (BOUNDS);

CREATE TABLE IF NOT EXISTS BUSLANES.GEOMETRY_UPDATE_RUNS
(
    ID                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCES             JSONB NOT NULL,
    CHECKSUM            TEXT NOT NULL,
    DOWNLOADED_BYTES    BIGINT NOT NULL CHECK (DOWNLOADED_BYTES >= 0),
    PARSED_LINES        INTEGER NOT NULL CHECK (PARSED_LINES >= 0),
    IMPORTED_GEOMETRIES INTEGER NOT NULL CHECK (IMPORTED_GEOMETRIES >= 0),
    SKIPPED_WITHOUT_CITY INTEGER NOT NULL CHECK (SKIPPED_WITHOUT_CITY >= 0),
    RESOLVED_AMBIGUOUS  INTEGER NOT NULL CHECK (RESOLVED_AMBIGUOUS >= 0),
    IGNORED_NON_LINES   INTEGER NOT NULL CHECK (IGNORED_NON_LINES >= 0),
    CREATED_AT          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE BUSLANES.CITY_MATCH_BOUNDS IS
    'Stable city bounding boxes used for KML assignment; never recalculated from imported lines.';
COMMENT ON TABLE BUSLANES.GEOMETRY_UPDATE_RUNS IS
    'Audit log for successful atomic replacements performed by the protected KML update API.';
