SET SEARCH_PATH = BUSLANES, PUBLIC;

DROP TABLE IF EXISTS BUSLANES.CITY_MATCH_BOUNDS;

ALTER TABLE BUSLANES.CITIES
    ALTER COLUMN BOUNDS DROP NOT NULL;

UPDATE BUSLANES.CITIES
SET BOUNDS = NULL;

CREATE TABLE IF NOT EXISTS BUSLANES.CITY_BOUNDARIES
(
    CITY_ID       BIGINT PRIMARY KEY REFERENCES BUSLANES.CITIES (ID) ON DELETE CASCADE,
    OSM_TYPE      TEXT NOT NULL CHECK (OSM_TYPE IN ('way', 'relation')),
    OSM_ID        BIGINT NOT NULL,
    OSM_NAME      TEXT NOT NULL,
    TAGS          JSONB NOT NULL DEFAULT '{}'::JSONB,
    GEOM          PUBLIC.GEOMETRY(MultiPolygon, 4326) NOT NULL,
    BOUNDS        PUBLIC.GEOMETRY(Polygon, 4326) NOT NULL,
    OSM_TIMESTAMP TIMESTAMPTZ,
    UPDATED_AT    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT CITY_BOUNDARIES_OSM_OBJECT_UNIQUE UNIQUE (OSM_TYPE, OSM_ID),
    CONSTRAINT CITY_BOUNDARIES_GEOM_VALID CHECK (ST_ISVALID(GEOM)),
    CONSTRAINT CITY_BOUNDARIES_BOUNDS_VALID CHECK (ST_ISVALID(BOUNDS))
);

CREATE INDEX IF NOT EXISTS CITY_BOUNDARIES_GEOM_GIST_IDX
    ON BUSLANES.CITY_BOUNDARIES USING GIST (GEOM);
CREATE INDEX IF NOT EXISTS CITY_BOUNDARIES_BOUNDS_GIST_IDX
    ON BUSLANES.CITY_BOUNDARIES USING GIST (BOUNDS);

CREATE TABLE IF NOT EXISTS BUSLANES.OSM_CITY_UPDATE_RUNS
(
    ID               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCE_URL       TEXT NOT NULL,
    CHECKSUM         TEXT NOT NULL,
    DOWNLOADED_BYTES BIGINT NOT NULL CHECK (DOWNLOADED_BYTES >= 0),
    SOURCE_ELEMENTS  INTEGER NOT NULL CHECK (SOURCE_ELEMENTS >= 0),
    IMPORTED_CITIES  INTEGER NOT NULL CHECK (IMPORTED_CITIES >= 0),
    IGNORED_ELEMENTS INTEGER NOT NULL CHECK (IGNORED_ELEMENTS >= 0),
    OSM_TIMESTAMP    TIMESTAMPTZ,
    CREATED_AT       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE BUSLANES.CITY_BOUNDARIES IS
    'Russian OSM way/relation geometries with name and place=city; independent from bus-lane lines.';
COMMENT ON COLUMN BUSLANES.CITY_BOUNDARIES.BOUNDS IS
    'OSM-derived bounding polygon used to assign imported KML lines to cities.';
COMMENT ON COLUMN BUSLANES.CITIES.BOUNDS IS
    'Deprecated compatibility column; city viewport bounds are stored in city_boundaries and never derived from bus-lane lines.';
