SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.CITY_BOUNDARIES
    ADD COLUMN IF NOT EXISTS ID BIGINT GENERATED ALWAYS AS IDENTITY;

ALTER TABLE BUSLANES.CITY_BOUNDARIES
    DROP CONSTRAINT IF EXISTS CITY_BOUNDARIES_PKEY;

ALTER TABLE BUSLANES.CITY_BOUNDARIES
    ADD CONSTRAINT CITY_BOUNDARIES_PKEY PRIMARY KEY (ID);

ALTER TABLE BUSLANES.CITY_BOUNDARIES
    ALTER COLUMN CITY_ID DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS PLACE_TYPE TEXT;

UPDATE BUSLANES.CITY_BOUNDARIES
SET PLACE_TYPE = COALESCE(NULLIF(TAGS ->> 'place', ''), 'city')
WHERE PLACE_TYPE IS NULL;

ALTER TABLE BUSLANES.CITY_BOUNDARIES
    ALTER COLUMN PLACE_TYPE SET NOT NULL;

DO $MIGRATION$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM PG_CONSTRAINT
        WHERE CONRELID = 'BUSLANES.CITY_BOUNDARIES'::REGCLASS
          AND CONNAME = 'city_boundaries_place_type_check'
    ) THEN
        ALTER TABLE BUSLANES.CITY_BOUNDARIES
            ADD CONSTRAINT CITY_BOUNDARIES_PLACE_TYPE_CHECK
                CHECK (PLACE_TYPE IN ('city', 'town'));
    END IF;
END
$MIGRATION$;

CREATE UNIQUE INDEX IF NOT EXISTS CITY_BOUNDARIES_CITY_ID_UNIQUE_IDX
    ON BUSLANES.CITY_BOUNDARIES (CITY_ID)
    WHERE CITY_ID IS NOT NULL;
CREATE INDEX IF NOT EXISTS CITY_BOUNDARIES_NAME_IDX
    ON BUSLANES.CITY_BOUNDARIES (OSM_NAME);
CREATE INDEX IF NOT EXISTS CITY_BOUNDARIES_PLACE_TYPE_IDX
    ON BUSLANES.CITY_BOUNDARIES (PLACE_TYPE);

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ALTER COLUMN CITY_ID DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS BOUNDARY_ID BIGINT;

UPDATE BUSLANES.CITY_GEOMETRIES AS GEOMETRY
SET BOUNDARY_ID = BOUNDARY.ID
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
WHERE BOUNDARY.CITY_ID = GEOMETRY.CITY_ID
  AND GEOMETRY.BOUNDARY_ID IS NULL;

DO $MIGRATION$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM PG_CONSTRAINT
        WHERE CONRELID = 'BUSLANES.CITY_GEOMETRIES'::REGCLASS
          AND CONNAME = 'city_geometries_boundary_id_fkey'
    ) THEN
        ALTER TABLE BUSLANES.CITY_GEOMETRIES
            ADD CONSTRAINT CITY_GEOMETRIES_BOUNDARY_ID_FKEY
                FOREIGN KEY (BOUNDARY_ID)
                REFERENCES BUSLANES.CITY_BOUNDARIES (ID)
                ON DELETE SET NULL;
    END IF;
END
$MIGRATION$;

CREATE INDEX IF NOT EXISTS CITY_GEOMETRIES_BOUNDARY_ID_IDX
    ON BUSLANES.CITY_GEOMETRIES (BOUNDARY_ID);

ALTER TABLE BUSLANES.GEOMETRY_UPDATE_RUNS
    ADD COLUMN IF NOT EXISTS CITY_BUFFER_M INTEGER NOT NULL DEFAULT 0
        CHECK (CITY_BUFFER_M >= 0);

ALTER TABLE BUSLANES.OSM_CITY_UPDATE_RUNS
    ADD COLUMN IF NOT EXISTS CITY_PLACES INTEGER NOT NULL DEFAULT 0
        CHECK (CITY_PLACES >= 0),
    ADD COLUMN IF NOT EXISTS TOWN_PLACES INTEGER NOT NULL DEFAULT 0
        CHECK (TOWN_PLACES >= 0),
    ADD COLUMN IF NOT EXISTS DUPLICATE_NAMES INTEGER NOT NULL DEFAULT 0
        CHECK (DUPLICATE_NAMES >= 0);

UPDATE BUSLANES.OSM_CITY_UPDATE_RUNS
SET CITY_PLACES = IMPORTED_CITIES
WHERE CITY_PLACES = 0
  AND TOWN_PLACES = 0;

COMMENT ON TABLE BUSLANES.CITY_BOUNDARIES IS
    'Russian OSM way/relation polygons with non-empty name and place=city/town; names need not be unique.';
COMMENT ON COLUMN BUSLANES.CITY_BOUNDARIES.CITY_ID IS
    'Optional link to a ranked city; OSM places remain distinct through boundary ID and OSM object ID.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.BOUNDARY_ID IS
    'Exact OSM polygon selected by positive line/polygon overlap.';
COMMENT ON COLUMN BUSLANES.GEOMETRY_UPDATE_RUNS.CITY_BUFFER_M IS
    'Geodesic buffer in metres applied to OSM polygons during KML matching.';
