SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.OSM_CITY_UPDATE_RUNS
    ADD COLUMN IF NOT EXISTS BATCH_SIZE INTEGER NOT NULL DEFAULT 0
        CHECK (BATCH_SIZE >= 0),
    ADD COLUMN IF NOT EXISTS BATCH_COUNT INTEGER NOT NULL DEFAULT 0
        CHECK (BATCH_COUNT >= 0);

COMMENT ON COLUMN BUSLANES.OSM_CITY_UPDATE_RUNS.BATCH_SIZE IS
    'Maximum number of indexed OSM objects requested in each sequential geometry batch.';
COMMENT ON COLUMN BUSLANES.OSM_CITY_UPDATE_RUNS.BATCH_COUNT IS
    'Number of geometry batches fully staged before the atomic boundary replacement.';
