SET SEARCH_PATH = BUSLANES, PUBLIC;

CREATE TABLE IF NOT EXISTS BUSLANES.ADMIN_TASK_SUCCESSES
(
    TASK_TYPE    TEXT PRIMARY KEY,
    TASK_ID      UUID,
    ENDPOINT     TEXT NOT NULL,
    COMPLETED_AT TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE BUSLANES.ADMIN_TASK_SUCCESSES IS
    'Last successful non-dry-run execution time for each protected admin update type.';

INSERT INTO BUSLANES.ADMIN_TASK_SUCCESSES (
    TASK_TYPE,
    TASK_ID,
    ENDPOINT,
    COMPLETED_AT
)
SELECT 'kml-update',
       NULL,
       '/api/admin/update',
       MAX(CREATED_AT)
FROM BUSLANES.GEOMETRY_UPDATE_RUNS
HAVING MAX(CREATED_AT) IS NOT NULL
ON CONFLICT (TASK_TYPE) DO UPDATE
SET COMPLETED_AT = GREATEST(
        ADMIN_TASK_SUCCESSES.COMPLETED_AT,
        EXCLUDED.COMPLETED_AT
    );

INSERT INTO BUSLANES.ADMIN_TASK_SUCCESSES (
    TASK_TYPE,
    TASK_ID,
    ENDPOINT,
    COMPLETED_AT
)
SELECT 'osm-city-update',
       NULL,
       '/api/admin/update/cities',
       MAX(CREATED_AT)
FROM BUSLANES.OSM_CITY_UPDATE_RUNS
HAVING MAX(CREATED_AT) IS NOT NULL
ON CONFLICT (TASK_TYPE) DO UPDATE
SET COMPLETED_AT = GREATEST(
        ADMIN_TASK_SUCCESSES.COMPLETED_AT,
        EXCLUDED.COMPLETED_AT
    );

INSERT INTO BUSLANES.ADMIN_TASK_SUCCESSES (
    TASK_TYPE,
    TASK_ID,
    ENDPOINT,
    COMPLETED_AT
)
SELECT 'population-update',
       NULL,
       '/api/admin/populations',
       MAX(UPDATED_AT)
FROM BUSLANES.CITY_POPULATIONS
HAVING MAX(UPDATED_AT) IS NOT NULL
ON CONFLICT (TASK_TYPE) DO UPDATE
SET COMPLETED_AT = GREATEST(
        ADMIN_TASK_SUCCESSES.COMPLETED_AT,
        EXCLUDED.COMPLETED_AT
    );
