SET SEARCH_PATH = BUSLANES, PUBLIC;

CREATE TABLE IF NOT EXISTS BUSLANES.LINE_TYPES
(
    ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE       TEXT NOT NULL UNIQUE,
    NAME       TEXT NOT NULL,
    COLOR      TEXT NOT NULL DEFAULT '#045b69',
    LINE_STYLE TEXT NOT NULL DEFAULT 'solid',
    WIDTH      DOUBLE PRECISION NOT NULL DEFAULT 4,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT LINE_TYPES_CODE_CHECK CHECK (
        LENGTH(BTRIM(CODE)) BETWEEN 1 AND 64
        AND CODE = BTRIM(CODE)
    ),
    CONSTRAINT LINE_TYPES_NAME_CHECK CHECK (
        LENGTH(BTRIM(NAME)) BETWEEN 1 AND 120
        AND NAME = BTRIM(NAME)
    ),
    CONSTRAINT LINE_TYPES_COLOR_CHECK CHECK (
        COLOR ~ '^#[0-9A-Fa-f]{6}$'
    ),
    CONSTRAINT LINE_TYPES_STYLE_CHECK CHECK (
        LINE_STYLE IN ('solid', 'dashed', 'dotted')
    ),
    CONSTRAINT LINE_TYPES_WIDTH_CHECK CHECK (
        WIDTH >= 0.5 AND WIDTH <= 32
    )
);

INSERT INTO BUSLANES.LINE_TYPES (CODE, NAME, COLOR, LINE_STYLE, WIDTH)
VALUES ('default', 'Выделенные полосы', '#045b69', 'solid', 4)
ON CONFLICT (CODE) DO NOTHING;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ADD COLUMN IF NOT EXISTS LINE_TYPE_ID BIGINT;

UPDATE BUSLANES.CITY_GEOMETRIES AS GEOMETRY
SET LINE_TYPE_ID = LINE_TYPE.ID
FROM BUSLANES.LINE_TYPES AS LINE_TYPE
WHERE LINE_TYPE.CODE = 'default'
  AND GEOMETRY.LINE_TYPE_ID IS NULL;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ALTER COLUMN LINE_TYPE_ID SET NOT NULL;

DO $MIGRATION$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM PG_CONSTRAINT
        WHERE CONRELID = 'BUSLANES.CITY_GEOMETRIES'::REGCLASS
          AND CONNAME = 'city_geometries_line_type_id_fkey'
    ) THEN
        ALTER TABLE BUSLANES.CITY_GEOMETRIES
            ADD CONSTRAINT CITY_GEOMETRIES_LINE_TYPE_ID_FKEY
                FOREIGN KEY (LINE_TYPE_ID)
                REFERENCES BUSLANES.LINE_TYPES (ID)
                ON DELETE RESTRICT;
    END IF;
END
$MIGRATION$;

CREATE INDEX IF NOT EXISTS CITY_GEOMETRIES_LINE_TYPE_ID_IDX
    ON BUSLANES.CITY_GEOMETRIES (LINE_TYPE_ID);

COMMENT ON TABLE BUSLANES.LINE_TYPES IS
    'Portable line type dictionary with map legend label and rendering style.';
COMMENT ON COLUMN BUSLANES.LINE_TYPES.CODE IS
    'Stable portable type key used by KML configuration and GeoJSON transfer.';
COMMENT ON COLUMN BUSLANES.LINE_TYPES.LINE_STYLE IS
    'Map rendering style: solid, dashed or dotted.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.LINE_TYPE_ID IS
    'Line type and rendering style reference; legacy rows use the default type.';
