SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    ADD COLUMN IF NOT EXISTS YANDEX_METRIKA_ID TEXT,
    ADD COLUMN IF NOT EXISTS GOOGLE_ANALYTICS_ID TEXT;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    DROP CONSTRAINT IF EXISTS PROJECT_SETTINGS_YANDEX_METRIKA_ID_CHECK,
    ADD CONSTRAINT PROJECT_SETTINGS_YANDEX_METRIKA_ID_CHECK CHECK (
        YANDEX_METRIKA_ID IS NULL OR
        YANDEX_METRIKA_ID ~ '^[1-9][0-9]{0,14}$'
    ),
    DROP CONSTRAINT IF EXISTS PROJECT_SETTINGS_GOOGLE_ANALYTICS_ID_CHECK,
    ADD CONSTRAINT PROJECT_SETTINGS_GOOGLE_ANALYTICS_ID_CHECK CHECK (
        GOOGLE_ANALYTICS_ID IS NULL OR
        GOOGLE_ANALYTICS_ID ~ '^G-[A-Z0-9]{4,32}$'
    );

COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.YANDEX_METRIKA_ID IS
    'Optional Yandex Metrica counter id. NULL disables Yandex analytics.';
COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.GOOGLE_ANALYTICS_ID IS
    'Optional Google Analytics 4 Measurement ID (G-...). NULL disables Google analytics.';
