SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    DROP CONSTRAINT IF EXISTS PROJECT_SETTINGS_YANDEX_METRIKA_ID_CHECK,
    ADD CONSTRAINT PROJECT_SETTINGS_YANDEX_METRIKA_ID_CHECK CHECK (
        YANDEX_METRIKA_ID IS NULL OR
        YANDEX_METRIKA_ID ~ '^[1-9][0-9]{0,14}$'
    );

COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.YANDEX_METRIKA_ID IS
    'Optional Yandex Metrica counter id (1-15 digits). NULL disables Yandex analytics.';
