SET SEARCH_PATH = BUSLANES, PUBLIC;

DO $MIGRATION$
DECLARE
    DUPLICATES TEXT;
BEGIN
    SELECT STRING_AGG(FORMAT('%s (%s)', NORMALIZED_NAME, ROW_COUNT), ', ' ORDER BY NORMALIZED_NAME)
    INTO DUPLICATES
    FROM (
        SELECT LOWER(BTRIM(NAME)) AS NORMALIZED_NAME, COUNT(*) AS ROW_COUNT
        FROM BUSLANES.LINE_TYPES
        GROUP BY LOWER(BTRIM(NAME))
        HAVING COUNT(*) > 1
    ) AS DUPLICATE_NAMES;

    IF DUPLICATES IS NOT NULL THEN
        RAISE EXCEPTION 'Cannot enforce unique line type names; duplicates ignoring case/outer spaces: %', DUPLICATES;
    END IF;
END
$MIGRATION$;

UPDATE BUSLANES.LINE_TYPES
SET NAME = BTRIM(NAME),
    UPDATED_AT = NOW()
WHERE NAME <> BTRIM(NAME);

CREATE UNIQUE INDEX IF NOT EXISTS LINE_TYPES_NAME_CI_UIDX
    ON BUSLANES.LINE_TYPES (LOWER(BTRIM(NAME)));

UPDATE BUSLANES.CITY_GEOMETRIES
SET PROPERTIES = (PROPERTIES - 'lineType') #- '{_dtpstat,lineType}'
WHERE PROPERTIES ? 'lineType'
   OR (PROPERTIES -> '_dtpstat') ? 'lineType';

COMMENT ON INDEX BUSLANES.LINE_TYPES_NAME_CI_UIDX IS
    'Line type display names are unique ignoring case and leading/trailing spaces.';
