SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    ADD COLUMN IF NOT EXISTS SHOW_LINE_LABELS BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS BUSLANES.ADMIN_USERS
(
    ID                          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME                    TEXT        NOT NULL,
    EMAIL                       TEXT,
    PASSWORD_HASH               TEXT        NOT NULL,
    CAN_MANAGE_DATA             BOOLEAN     NOT NULL DEFAULT FALSE,
    CAN_MANAGE_INTERFACE        BOOLEAN     NOT NULL DEFAULT FALSE,
    IS_SUPERUSER                BOOLEAN     NOT NULL DEFAULT FALSE,
    IS_BLOCKED                  BOOLEAN     NOT NULL DEFAULT FALSE,
    FAILED_LOGIN_COUNT          INTEGER     NOT NULL DEFAULT 0 CHECK (FAILED_LOGIN_COUNT >= 0),
    FAILED_LOGIN_WINDOW_STARTED_AT TIMESTAMPTZ,
    LOCKED_UNTIL                TIMESTAMPTZ,
    LAST_LOGIN_AT               TIMESTAMPTZ,
    PASSWORD_CHANGED_AT         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CREATED_AT                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ADMIN_USERS_USERNAME_NOT_BLANK CHECK (CHAR_LENGTH(BTRIM(USERNAME)) BETWEEN 1 AND 64),
    CONSTRAINT ADMIN_USERS_EMAIL_LENGTH CHECK (EMAIL IS NULL OR CHAR_LENGTH(EMAIL) <= 320)
);

CREATE UNIQUE INDEX IF NOT EXISTS ADMIN_USERS_USERNAME_CI_UIDX
    ON BUSLANES.ADMIN_USERS (LOWER(BTRIM(USERNAME)));

CREATE TABLE IF NOT EXISTS BUSLANES.ADMIN_SECURITY_SETTINGS
(
    ID                     SMALLINT    PRIMARY KEY DEFAULT 1 CHECK (ID = 1),
    MAX_FAILED_ATTEMPTS    INTEGER     NOT NULL DEFAULT 5 CHECK (MAX_FAILED_ATTEMPTS BETWEEN 1 AND 100),
    FAILURE_WINDOW_SECONDS INTEGER     NOT NULL DEFAULT 900 CHECK (FAILURE_WINDOW_SECONDS BETWEEN 10 AND 86400),
    LOCKOUT_SECONDS        INTEGER     NOT NULL DEFAULT 900 CHECK (LOCKOUT_SECONDS BETWEEN 10 AND 604800),
    UPDATED_AT             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO BUSLANES.ADMIN_SECURITY_SETTINGS (
    ID,
    MAX_FAILED_ATTEMPTS,
    FAILURE_WINDOW_SECONDS,
    LOCKOUT_SECONDS
)
VALUES (1, 5, 900, 900)
ON CONFLICT (ID) DO NOTHING;

CREATE TABLE IF NOT EXISTS BUSLANES.ADMIN_AUDIT_LOG
(
    ID             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CREATED_AT     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    EVENT_TYPE     TEXT        NOT NULL,
    OPERATION_TYPE TEXT        NOT NULL,
    STATUS         TEXT        NOT NULL,
    DURATION_MS    BIGINT      CHECK (DURATION_MS IS NULL OR DURATION_MS >= 0),
    IP_ADDRESS     TEXT,
    USER_ID        BIGINT      REFERENCES BUSLANES.ADMIN_USERS (ID) ON DELETE SET NULL,
    USERNAME       TEXT,
    DETAILS        JSONB       NOT NULL DEFAULT '{}'::JSONB
);

CREATE INDEX IF NOT EXISTS ADMIN_AUDIT_LOG_CREATED_AT_IDX
    ON BUSLANES.ADMIN_AUDIT_LOG (CREATED_AT DESC, ID DESC);
CREATE INDEX IF NOT EXISTS ADMIN_AUDIT_LOG_USER_ID_IDX
    ON BUSLANES.ADMIN_AUDIT_LOG (USER_ID, CREATED_AT DESC);

COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.SHOW_LINE_LABELS IS
    'Whether the public map draws persistent placemarkName labels along line geometries.';
COMMENT ON TABLE BUSLANES.ADMIN_USERS IS
    'Database-backed administrators. Environment credentials are used only to bootstrap the first superuser.';
COMMENT ON TABLE BUSLANES.ADMIN_SECURITY_SETTINGS IS
    'Singleton configurable failed-login window and temporary account lockout policy.';
COMMENT ON TABLE BUSLANES.ADMIN_AUDIT_LOG IS
    'Append-only administrator authentication and operation audit trail.';
