SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.ADMIN_USERS
    ADD COLUMN IF NOT EXISTS IS_BOOTSTRAP BOOLEAN NOT NULL DEFAULT FALSE;

WITH FIRST_USER AS (
    SELECT ID
    FROM BUSLANES.ADMIN_USERS
    ORDER BY CREATED_AT, ID
    LIMIT 1
)
UPDATE BUSLANES.ADMIN_USERS AS USERS
SET IS_BOOTSTRAP = TRUE,
    IS_SUPERUSER = TRUE,
    CAN_MANAGE_DATA = TRUE,
    CAN_MANAGE_INTERFACE = TRUE,
    IS_BLOCKED = FALSE,
    UPDATED_AT = NOW()
FROM FIRST_USER
WHERE USERS.ID = FIRST_USER.ID
  AND NOT USERS.IS_BOOTSTRAP;

CREATE UNIQUE INDEX IF NOT EXISTS ADMIN_USERS_BOOTSTRAP_UIDX
    ON BUSLANES.ADMIN_USERS ((1))
    WHERE IS_BOOTSTRAP;

ALTER TABLE BUSLANES.ADMIN_USERS
    DROP CONSTRAINT IF EXISTS ADMIN_USERS_BOOTSTRAP_INVARIANT,
    ADD CONSTRAINT ADMIN_USERS_BOOTSTRAP_INVARIANT CHECK (
        NOT IS_BOOTSTRAP
        OR (
            IS_SUPERUSER
            AND CAN_MANAGE_DATA
            AND CAN_MANAGE_INTERFACE
            AND NOT IS_BLOCKED
        )
    );

CREATE OR REPLACE FUNCTION BUSLANES.PROTECT_BOOTSTRAP_ADMIN_USER()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.IS_BOOTSTRAP THEN
            RAISE EXCEPTION 'Bootstrap administrator cannot be deleted';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.IS_BOOTSTRAP THEN
        IF NOT NEW.IS_BOOTSTRAP
           OR NOT NEW.IS_SUPERUSER
           OR NOT NEW.CAN_MANAGE_DATA
           OR NOT NEW.CAN_MANAGE_INTERFACE
           OR NEW.IS_BLOCKED THEN
            RAISE EXCEPTION 'Bootstrap administrator cannot be blocked, demoted, or stripped of permissions';
        END IF;
    END IF;

    RETURN NEW;
END
$FUNCTION$;

DROP TRIGGER IF EXISTS ADMIN_USERS_PROTECT_BOOTSTRAP_TRG
    ON BUSLANES.ADMIN_USERS;
CREATE TRIGGER ADMIN_USERS_PROTECT_BOOTSTRAP_TRG
BEFORE UPDATE OR DELETE ON BUSLANES.ADMIN_USERS
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.PROTECT_BOOTSTRAP_ADMIN_USER();

COMMENT ON COLUMN BUSLANES.ADMIN_USERS.IS_BOOTSTRAP IS
    'Marks the first environment-bootstrapped administrator. This account cannot be manually blocked, deleted, demoted, or stripped of either administrative permission; temporary authentication lockout remains allowed.';
