SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.ADMIN_USERS
    ADD COLUMN IF NOT EXISTS DISPLAY_NAME TEXT,
    ADD COLUMN IF NOT EXISTS CAN_MANAGE_USERS BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS CAN_VIEW_AUDIT BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS CAN_MANAGE_SECURITY BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS MUST_CHANGE_PASSWORD BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS AVATAR_MIME TEXT,
    ADD COLUMN IF NOT EXISTS AVATAR_DATA BYTEA,
    ADD COLUMN IF NOT EXISTS MANUAL_BLOCKED_AT TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS MANUAL_BLOCKED_UNTIL TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS MANUAL_BLOCK_REASON TEXT,
    ADD COLUMN IF NOT EXISTS MANUAL_BLOCKED_BY BIGINT;

ALTER TABLE BUSLANES.ADMIN_USERS
    DROP CONSTRAINT IF EXISTS ADMIN_USERS_DISPLAY_NAME_LENGTH,
    ADD CONSTRAINT ADMIN_USERS_DISPLAY_NAME_LENGTH CHECK (
        DISPLAY_NAME IS NULL OR CHAR_LENGTH(BTRIM(DISPLAY_NAME)) BETWEEN 1 AND 160
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_USERS_AVATAR_MIME_CHECK,
    ADD CONSTRAINT ADMIN_USERS_AVATAR_MIME_CHECK CHECK (
        AVATAR_MIME IS NULL OR AVATAR_MIME IN ('image/png', 'image/jpeg', 'image/webp')
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_USERS_AVATAR_PAIR_CHECK,
    ADD CONSTRAINT ADMIN_USERS_AVATAR_PAIR_CHECK CHECK (
        (AVATAR_MIME IS NULL) = (AVATAR_DATA IS NULL)
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_USERS_MANUAL_BLOCK_REASON_LENGTH,
    ADD CONSTRAINT ADMIN_USERS_MANUAL_BLOCK_REASON_LENGTH CHECK (
        MANUAL_BLOCK_REASON IS NULL OR CHAR_LENGTH(MANUAL_BLOCK_REASON) <= 500
    );

DO $BLOCK$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM PG_CONSTRAINT
        WHERE CONNAME = 'admin_users_manual_blocked_by_fk'
          AND CONRELID = 'BUSLANES.ADMIN_USERS'::REGCLASS
    ) THEN
        ALTER TABLE BUSLANES.ADMIN_USERS
            ADD CONSTRAINT ADMIN_USERS_MANUAL_BLOCKED_BY_FK
            FOREIGN KEY (MANUAL_BLOCKED_BY)
            REFERENCES BUSLANES.ADMIN_USERS (ID)
            ON DELETE SET NULL;
    END IF;
END
$BLOCK$;

UPDATE BUSLANES.ADMIN_USERS
SET CAN_MANAGE_USERS = TRUE,
    CAN_VIEW_AUDIT = TRUE,
    CAN_MANAGE_SECURITY = TRUE,
    DISPLAY_NAME = COALESCE(DISPLAY_NAME, USERNAME),
    UPDATED_AT = NOW()
WHERE IS_BOOTSTRAP OR IS_SUPERUSER;

UPDATE BUSLANES.ADMIN_USERS
SET DISPLAY_NAME = USERNAME
WHERE DISPLAY_NAME IS NULL;

ALTER TABLE BUSLANES.ADMIN_SECURITY_SETTINGS
    ADD COLUMN IF NOT EXISTS IP_MAX_FAILED_ATTEMPTS INTEGER NOT NULL DEFAULT 20,
    ADD COLUMN IF NOT EXISTS IP_FAILURE_WINDOW_SECONDS INTEGER NOT NULL DEFAULT 900,
    ADD COLUMN IF NOT EXISTS IP_LOCKOUT_SECONDS INTEGER NOT NULL DEFAULT 3600,
    ADD COLUMN IF NOT EXISTS SESSION_IDLE_SECONDS INTEGER NOT NULL DEFAULT 1800,
    ADD COLUMN IF NOT EXISTS SESSION_ABSOLUTE_SECONDS INTEGER NOT NULL DEFAULT 43200,
    ADD COLUMN IF NOT EXISTS AUDIT_RETENTION_DAYS INTEGER NOT NULL DEFAULT 365;

ALTER TABLE BUSLANES.ADMIN_SECURITY_SETTINGS
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_IP_MAX_FAILED_ATTEMPTS_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_IP_MAX_FAILED_ATTEMPTS_CHECK CHECK (
        IP_MAX_FAILED_ATTEMPTS BETWEEN 1 AND 1000
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_IP_FAILURE_WINDOW_SECONDS_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_IP_FAILURE_WINDOW_SECONDS_CHECK CHECK (
        IP_FAILURE_WINDOW_SECONDS BETWEEN 10 AND 86400
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_IP_LOCKOUT_SECONDS_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_IP_LOCKOUT_SECONDS_CHECK CHECK (
        IP_LOCKOUT_SECONDS BETWEEN 10 AND 604800
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_SESSION_IDLE_SECONDS_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_SESSION_IDLE_SECONDS_CHECK CHECK (
        SESSION_IDLE_SECONDS BETWEEN 60 AND 86400
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_SESSION_ABSOLUTE_SECONDS_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_SESSION_ABSOLUTE_SECONDS_CHECK CHECK (
        SESSION_ABSOLUTE_SECONDS BETWEEN 300 AND 2592000
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_AUDIT_RETENTION_DAYS_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_AUDIT_RETENTION_DAYS_CHECK CHECK (
        AUDIT_RETENTION_DAYS BETWEEN 0 AND 3650
    );

CREATE TABLE IF NOT EXISTS BUSLANES.ADMIN_SESSIONS
(
    ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID     BIGINT      NOT NULL REFERENCES BUSLANES.ADMIN_USERS (ID) ON DELETE CASCADE,
    TOKEN_HASH  BYTEA       NOT NULL UNIQUE,
    CREATED_AT  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    LAST_SEEN_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    EXPIRES_AT  TIMESTAMPTZ NOT NULL,
    IP_ADDRESS  INET,
    USER_AGENT  TEXT
);

CREATE INDEX IF NOT EXISTS ADMIN_SESSIONS_USER_ID_IDX
    ON BUSLANES.ADMIN_SESSIONS (USER_ID, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS ADMIN_SESSIONS_EXPIRES_AT_IDX
    ON BUSLANES.ADMIN_SESSIONS (EXPIRES_AT);

CREATE TABLE IF NOT EXISTS BUSLANES.ADMIN_LOGIN_IP_STATE
(
    IP_ADDRESS             INET PRIMARY KEY,
    FAILED_LOGIN_COUNT     INTEGER     NOT NULL DEFAULT 0 CHECK (FAILED_LOGIN_COUNT >= 0),
    FAILURE_WINDOW_STARTED_AT TIMESTAMPTZ,
    LOCKED_UNTIL           TIMESTAMPTZ,
    UPDATED_AT             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ADMIN_LOGIN_IP_STATE_LOCKED_UNTIL_IDX
    ON BUSLANES.ADMIN_LOGIN_IP_STATE (LOCKED_UNTIL)
    WHERE LOCKED_UNTIL IS NOT NULL;

CREATE TABLE IF NOT EXISTS BUSLANES.ADMIN_BLOCKED_IPS
(
    ID             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IP_ADDRESS     INET        NOT NULL,
    CREATED_AT     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    EXPIRES_AT     TIMESTAMPTZ,
    BLOCKED_BY     BIGINT      REFERENCES BUSLANES.ADMIN_USERS (ID) ON DELETE SET NULL,
    REASON         TEXT,
    SOURCE_AUDIT_ID BIGINT     REFERENCES BUSLANES.ADMIN_AUDIT_LOG (ID) ON DELETE SET NULL,
    CONSTRAINT ADMIN_BLOCKED_IPS_REASON_LENGTH CHECK (
        REASON IS NULL OR CHAR_LENGTH(REASON) <= 500
    )
);

CREATE INDEX IF NOT EXISTS ADMIN_BLOCKED_IPS_ADDRESS_IDX
    ON BUSLANES.ADMIN_BLOCKED_IPS (IP_ADDRESS, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS ADMIN_BLOCKED_IPS_EXPIRES_AT_IDX
    ON BUSLANES.ADMIN_BLOCKED_IPS (EXPIRES_AT)
    WHERE EXPIRES_AT IS NOT NULL;

CREATE INDEX IF NOT EXISTS ADMIN_AUDIT_LOG_EVENT_CREATED_IDX
    ON BUSLANES.ADMIN_AUDIT_LOG (EVENT_TYPE, CREATED_AT DESC, ID DESC);
CREATE INDEX IF NOT EXISTS ADMIN_AUDIT_LOG_OPERATION_CREATED_IDX
    ON BUSLANES.ADMIN_AUDIT_LOG (OPERATION_TYPE, CREATED_AT DESC, ID DESC);
CREATE INDEX IF NOT EXISTS ADMIN_AUDIT_LOG_STATUS_CREATED_IDX
    ON BUSLANES.ADMIN_AUDIT_LOG (STATUS, CREATED_AT DESC, ID DESC);
CREATE INDEX IF NOT EXISTS ADMIN_AUDIT_LOG_USERNAME_CREATED_IDX
    ON BUSLANES.ADMIN_AUDIT_LOG (USERNAME, CREATED_AT DESC, ID DESC);
CREATE INDEX IF NOT EXISTS ADMIN_AUDIT_LOG_IP_CREATED_IDX
    ON BUSLANES.ADMIN_AUDIT_LOG (IP_ADDRESS, CREATED_AT DESC, ID DESC);

COMMENT ON COLUMN BUSLANES.ADMIN_USERS.MUST_CHANGE_PASSWORD IS
    'When true, interactive sessions may access only the active profile/password/logout flow until the password is changed.';
COMMENT ON TABLE BUSLANES.ADMIN_SESSIONS IS
    'Interactive web-admin sessions. Only SHA-256 token hashes are stored; plaintext tokens exist only in the browser cookie.';
COMMENT ON TABLE BUSLANES.ADMIN_LOGIN_IP_STATE IS
    'Per-IP failed-login counters and temporary throttling state used together with per-account lockout.';
COMMENT ON TABLE BUSLANES.ADMIN_BLOCKED_IPS IS
    'Manual administrator IP blocks with optional expiration and audit provenance.';
