SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    ADD COLUMN IF NOT EXISTS MAPBOX_ACCESS_TOKEN TEXT,
    ADD COLUMN IF NOT EXISTS MAPBOX_ACCESS_TOKEN_INITIALIZED BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    DROP CONSTRAINT IF EXISTS PROJECT_SETTINGS_MAPBOX_ACCESS_TOKEN_CHECK,
    ADD CONSTRAINT PROJECT_SETTINGS_MAPBOX_ACCESS_TOKEN_CHECK CHECK (
        MAPBOX_ACCESS_TOKEN IS NULL
        OR (
            CHAR_LENGTH(MAPBOX_ACCESS_TOKEN) BETWEEN 20 AND 2048
            AND MAPBOX_ACCESS_TOKEN LIKE 'pk.%'
            AND MAPBOX_ACCESS_TOKEN !~ '[[:cntrl:][:space:]]'
        )
    );

COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.MAPBOX_ACCESS_TOKEN IS
    'Mapbox public access token used by the browser map. Admin APIs never return the token in plaintext.';
COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.MAPBOX_ACCESS_TOKEN_INITIALIZED IS
    'One-way bootstrap marker. MAPBOX_ACCESS_TOKEN from ENV is consumed only while this flag is false.';
