SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    ADD COLUMN IF NOT EXISTS CITY_MARKER_ICON BYTEA,
    ADD COLUMN IF NOT EXISTS CITY_MARKER_ICON_MIME TEXT,
    ADD COLUMN IF NOT EXISTS CITY_MARKER_ICON_WIDTH SMALLINT,
    ADD COLUMN IF NOT EXISTS CITY_MARKER_ICON_HEIGHT SMALLINT;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    DROP CONSTRAINT IF EXISTS PROJECT_SETTINGS_CITY_MARKER_ICON_CHECK,
    ADD CONSTRAINT PROJECT_SETTINGS_CITY_MARKER_ICON_CHECK CHECK (
        (
            CITY_MARKER_ICON IS NULL
            AND CITY_MARKER_ICON_MIME IS NULL
            AND CITY_MARKER_ICON_WIDTH IS NULL
            AND CITY_MARKER_ICON_HEIGHT IS NULL
        )
        OR (
            CITY_MARKER_ICON IS NOT NULL
            AND CITY_MARKER_ICON_MIME = 'image/png'
            AND OCTET_LENGTH(CITY_MARKER_ICON) BETWEEN 1 AND 262144
            AND CITY_MARKER_ICON_WIDTH BETWEEN 16 AND 256
            AND CITY_MARKER_ICON_HEIGHT = CITY_MARKER_ICON_WIDTH
        )
    );

COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.CITY_MARKER_ICON IS
    'Optional custom PNG used for city markers below the line-data zoom threshold.';
COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.CITY_MARKER_ICON_MIME IS
    'MIME type of the configured city marker icon. Only image/png is accepted.';
COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.CITY_MARKER_ICON_WIDTH IS
    'Validated width of the configured square city marker icon in pixels.';
COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.CITY_MARKER_ICON_HEIGHT IS
    'Validated height of the configured square city marker icon in pixels.';
