SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE PROJECT_SETTINGS
    ADD COLUMN IF NOT EXISTS THEME_PRESET TEXT NOT NULL DEFAULT 'classic';

ALTER TABLE PROJECT_SETTINGS
    DROP CONSTRAINT IF EXISTS PROJECT_SETTINGS_THEME_PRESET_CHECK,
    ADD CONSTRAINT PROJECT_SETTINGS_THEME_PRESET_CHECK CHECK (
        THEME_PRESET IN ('retro', 'classic', 'modern')
    );

COMMENT ON COLUMN PROJECT_SETTINGS.THEME_PRESET IS
    'Built-in public UI theme preset: retro, classic or modern.';
