SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.REPORT_CONFIG
    ADD COLUMN IF NOT EXISTS RANK_SORT JSONB;

UPDATE BUSLANES.REPORT_CONFIG
SET RANK_SORT = JSONB_BUILD_ARRAY(
    JSONB_BUILD_OBJECT(
        'metricKey', RANK_METRIC_KEY,
        'direction', RANK_DIRECTION
    )
)
WHERE RANK_SORT IS NULL;

ALTER TABLE BUSLANES.REPORT_CONFIG
    ALTER COLUMN RANK_SORT SET NOT NULL;

DO $MIGRATION$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM PG_CONSTRAINT
        WHERE CONRELID = 'BUSLANES.REPORT_CONFIG'::REGCLASS
          AND CONNAME = 'report_config_rank_sort_check'
    ) THEN
        ALTER TABLE BUSLANES.REPORT_CONFIG
            ADD CONSTRAINT REPORT_CONFIG_RANK_SORT_CHECK CHECK (
                JSONB_TYPEOF(RANK_SORT) = 'array'
                AND JSONB_ARRAY_LENGTH(RANK_SORT) BETWEEN 1 AND 8
            );
    END IF;
END
$MIGRATION$;

COMMENT ON COLUMN BUSLANES.REPORT_CONFIG.RANK_SORT IS
    'Ordered ranking criteria. Each item contains metricKey and asc/desc direction; earlier items have higher sort priority.';
