SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    ADD COLUMN IF NOT EXISTS PUBLIC_DOWNLOAD_NAME TEXT NOT NULL DEFAULT 'bus-lanes';

DO $MIGRATION$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM PG_CONSTRAINT
        WHERE CONRELID = 'BUSLANES.PROJECT_SETTINGS'::REGCLASS
          AND CONNAME = 'project_settings_public_download_name_check'
    ) THEN
        ALTER TABLE BUSLANES.PROJECT_SETTINGS
            ADD CONSTRAINT PROJECT_SETTINGS_PUBLIC_DOWNLOAD_NAME_CHECK CHECK (
                CHAR_LENGTH(BTRIM(PUBLIC_DOWNLOAD_NAME)) BETWEEN 1 AND 120
            );
    END IF;
END
$MIGRATION$;

COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.PUBLIC_DOWNLOAD_NAME IS
    'Base file name used in Content-Disposition for public GeoJSON and CSV downloads; extensions are added by the server.';
