SET SEARCH_PATH = BUSLANES, PUBLIC;

-- V023 merged unrelated OSM relations solely because their derived names
-- matched. OSM object identity is (osm_type, osm_id); a relation already
-- contains its member ways and must never be merged with another relation by
-- text name.
DROP TRIGGER IF EXISTS CITY_BOUNDARIES_NORMALIZE_RELATIONS
    ON BUSLANES.CITY_BOUNDARIES;
DROP FUNCTION IF EXISTS BUSLANES.NORMALIZE_CITY_BOUNDARY_RELATIONS_TRIGGER();
DROP FUNCTION IF EXISTS BUSLANES.NORMALIZE_CITY_BOUNDARY_RELATIONS();

-- FULL_NAME and its index belonged to the incorrect cross-object grouping
-- model from V023. Source names remain in OSM_NAME/TAGS, while administrator
-- identity is stored explicitly in DISPLAY_NAME/DISPLAY_TYPE below.
DROP INDEX IF EXISTS BUSLANES.CITY_BOUNDARIES_LOGICAL_NAME_IDX;
ALTER TABLE BUSLANES.CITY_BOUNDARIES
    DROP COLUMN IF EXISTS FULL_NAME;

DROP TRIGGER IF EXISTS CITY_BOUNDARIES_SYNC_CITY_FULL_NAME
    ON BUSLANES.CITY_BOUNDARIES;
DROP FUNCTION IF EXISTS BUSLANES.SYNC_CITY_FULL_NAME_FROM_BOUNDARY();

ALTER TABLE BUSLANES.CITY_BOUNDARIES
    DROP CONSTRAINT IF EXISTS CITY_BOUNDARIES_PLACE_TYPE_CHECK,
    ALTER COLUMN PLACE_TYPE DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS ADMIN_LEVEL SMALLINT,
    ADD COLUMN IF NOT EXISTS IS_ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS DISPLAY_NAME TEXT,
    ADD COLUMN IF NOT EXISTS DISPLAY_TYPE TEXT,
    ADD COLUMN IF NOT EXISTS PARENT_ID BIGINT,
    ADD COLUMN IF NOT EXISTS AREA_M2 DOUBLE PRECISION;

UPDATE BUSLANES.CITY_BOUNDARIES
SET ADMIN_LEVEL = CASE
        WHEN TAGS ->> 'admin_level' ~ '^[0-9]+$'
            THEN (TAGS ->> 'admin_level')::SMALLINT
        ELSE NULL
    END,
    DISPLAY_NAME = COALESCE(
        NULLIF(BTRIM(TAGS ->> 'name:ru'), ''),
        NULLIF(BTRIM(OSM_NAME), ''),
        OSM_TYPE || '/' || OSM_ID
    ),
    DISPLAY_TYPE = COALESCE(NULLIF(BTRIM(PLACE_TYPE), ''), 'administrative'),
    AREA_M2 = ST_AREA(GEOM::GEOGRAPHY);

ALTER TABLE BUSLANES.CITY_BOUNDARIES
    ALTER COLUMN DISPLAY_NAME SET NOT NULL,
    ALTER COLUMN DISPLAY_TYPE SET NOT NULL,
    ALTER COLUMN AREA_M2 SET NOT NULL;

ALTER TABLE BUSLANES.CITY_BOUNDARIES
    ADD CONSTRAINT CITY_BOUNDARIES_PLACE_TYPE_CHECK
        CHECK (PLACE_TYPE IS NULL OR PLACE_TYPE IN ('city', 'town')),
    ADD CONSTRAINT CITY_BOUNDARIES_ADMIN_LEVEL_CHECK
        CHECK (ADMIN_LEVEL IS NULL OR ADMIN_LEVEL BETWEEN 1 AND 20),
    ADD CONSTRAINT CITY_BOUNDARIES_DISPLAY_NAME_CHECK
        CHECK (BTRIM(DISPLAY_NAME) <> ''),
    ADD CONSTRAINT CITY_BOUNDARIES_DISPLAY_TYPE_CHECK
        CHECK (BTRIM(DISPLAY_TYPE) <> ''),
    ADD CONSTRAINT CITY_BOUNDARIES_AREA_M2_CHECK
        CHECK (AREA_M2 > 0);

DO $MIGRATION$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM PG_CONSTRAINT
        WHERE CONRELID = 'BUSLANES.CITY_BOUNDARIES'::REGCLASS
          AND CONNAME = 'city_boundaries_parent_id_fkey'
    ) THEN
        ALTER TABLE BUSLANES.CITY_BOUNDARIES
            ADD CONSTRAINT CITY_BOUNDARIES_PARENT_ID_FKEY
                FOREIGN KEY (PARENT_ID)
                REFERENCES BUSLANES.CITY_BOUNDARIES (ID)
                ON DELETE SET NULL;
    END IF;
END
$MIGRATION$;

CREATE INDEX IF NOT EXISTS CITY_BOUNDARIES_PARENT_ID_IDX
    ON BUSLANES.CITY_BOUNDARIES (PARENT_ID);
CREATE INDEX IF NOT EXISTS CITY_BOUNDARIES_ACTIVE_IDX
    ON BUSLANES.CITY_BOUNDARIES (IS_ACTIVE)
    WHERE IS_ACTIVE;
CREATE INDEX IF NOT EXISTS CITY_BOUNDARIES_ADMIN_LEVEL_IDX
    ON BUSLANES.CITY_BOUNDARIES (ADMIN_LEVEL)
    WHERE ADMIN_LEVEL IS NOT NULL;

WITH RANKED AS (
    SELECT
        ID,
        ROW_NUMBER() OVER (
            PARTITION BY
                LOWER(REGEXP_REPLACE(DISPLAY_TYPE, '[[:space:]]+', '', 'g')),
                LOWER(REGEXP_REPLACE(DISPLAY_NAME, '[[:space:]]+', '', 'g'))
            ORDER BY
                (CITY_ID IS NOT NULL) DESC,
                (OSM_TYPE = 'relation') DESC,
                AREA_M2 DESC,
                ID
        ) AS RN
    FROM BUSLANES.CITY_BOUNDARIES
    WHERE PLACE_TYPE IN ('city', 'town')
)
UPDATE BUSLANES.CITY_BOUNDARIES AS BOUNDARY
SET IS_ACTIVE = (RANKED.RN = 1)
FROM RANKED
WHERE RANKED.ID = BOUNDARY.ID;

CREATE UNIQUE INDEX IF NOT EXISTS CITY_BOUNDARIES_ACTIVE_DISPLAY_UNIQUE_IDX
    ON BUSLANES.CITY_BOUNDARIES (
        LOWER(REGEXP_REPLACE(DISPLAY_TYPE, '[[:space:]]+', '', 'g')),
        LOWER(REGEXP_REPLACE(DISPLAY_NAME, '[[:space:]]+', '', 'g'))
    )
    WHERE IS_ACTIVE;

-- Inactive OSM objects may retain their historical city link while another
-- exact boundary becomes active for the same application city.
DROP INDEX IF EXISTS BUSLANES.CITY_BOUNDARIES_CITY_ID_UNIQUE_IDX;
CREATE UNIQUE INDEX CITY_BOUNDARIES_CITY_ID_UNIQUE_IDX
    ON BUSLANES.CITY_BOUNDARIES (CITY_ID)
    WHERE CITY_ID IS NOT NULL AND IS_ACTIVE;

ALTER TABLE BUSLANES.CITIES
    ADD COLUMN IF NOT EXISTS DISPLAY_TYPE TEXT NOT NULL DEFAULT 'city';

ALTER TABLE BUSLANES.CITIES
    DROP CONSTRAINT IF EXISTS CITIES_NAME_KEY;

UPDATE BUSLANES.CITIES AS CITY
SET DISPLAY_TYPE = BOUNDARY.DISPLAY_TYPE
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
WHERE BOUNDARY.CITY_ID = CITY.ID;

CREATE INDEX IF NOT EXISTS CITIES_DISPLAY_IDENTITY_IDX
    ON BUSLANES.CITIES (
        LOWER(REGEXP_REPLACE(DISPLAY_TYPE, '[[:space:]]+', '', 'g')),
        LOWER(REGEXP_REPLACE(NAME, '[[:space:]]+', '', 'g'))
    );

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    ADD COLUMN IF NOT EXISTS LARGE_CITY_POPULATION_THRESHOLD INTEGER
        NOT NULL DEFAULT 400000
        CHECK (LARGE_CITY_POPULATION_THRESHOLD > 0),
    ADD COLUMN IF NOT EXISTS LARGE_CITY_AREA_KM2_THRESHOLD DOUBLE PRECISION
        CHECK (
            LARGE_CITY_AREA_KM2_THRESHOLD IS NULL
            OR LARGE_CITY_AREA_KM2_THRESHOLD >= 0
        );

CREATE TABLE IF NOT EXISTS BUSLANES.OSM_IMPORT_SETTINGS
(
    ID                     SMALLINT PRIMARY KEY DEFAULT 1 CHECK (ID = 1),
    SOURCE_URL             TEXT NOT NULL DEFAULT 'https://overpass-api.de/api/interpreter',
    INCLUDE_CITY           BOOLEAN NOT NULL DEFAULT TRUE,
    INCLUDE_TOWN           BOOLEAN NOT NULL DEFAULT TRUE,
    INCLUDE_ADMINISTRATIVE BOOLEAN NOT NULL DEFAULT TRUE,
    ADMIN_LEVEL_MIN        SMALLINT NOT NULL DEFAULT 4 CHECK (ADMIN_LEVEL_MIN BETWEEN 1 AND 20),
    ADMIN_LEVEL_MAX        SMALLINT NOT NULL DEFAULT 8 CHECK (ADMIN_LEVEL_MAX BETWEEN 1 AND 20),
    BATCH_SIZE             INTEGER NOT NULL DEFAULT 50 CHECK (BATCH_SIZE BETWEEN 1 AND 1000),
    MIN_DELAY_MS           INTEGER NOT NULL DEFAULT 5000 CHECK (MIN_DELAY_MS BETWEEN 0 AND 300000),
    TIMEOUT_MS             INTEGER NOT NULL DEFAULT 600000 CHECK (TIMEOUT_MS BETWEEN 1000 AND 900000),
    QUERY_TIMEOUT_SECONDS  INTEGER NOT NULL DEFAULT 300 CHECK (QUERY_TIMEOUT_SECONDS BETWEEN 1 AND 600),
    MAX_BYTES              BIGINT NOT NULL DEFAULT 314572800 CHECK (MAX_BYTES BETWEEN 1024 AND 524288000),
    MAX_RETRIES            INTEGER NOT NULL DEFAULT 6 CHECK (MAX_RETRIES BETWEEN 0 AND 20),
    RETRY_BASE_DELAY_MS    INTEGER NOT NULL DEFAULT 30000 CHECK (RETRY_BASE_DELAY_MS BETWEEN 1000 AND 3600000),
    RETRY_MAX_DELAY_MS     INTEGER NOT NULL DEFAULT 240000 CHECK (RETRY_MAX_DELAY_MS BETWEEN 1000 AND 3600000),
    INITIALIZED            BOOLEAN NOT NULL DEFAULT FALSE,
    UPDATED_AT             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT OSM_IMPORT_SETTINGS_ADMIN_LEVEL_RANGE
        CHECK (ADMIN_LEVEL_MIN <= ADMIN_LEVEL_MAX),
    CONSTRAINT OSM_IMPORT_SETTINGS_RETRY_RANGE
        CHECK (RETRY_BASE_DELAY_MS <= RETRY_MAX_DELAY_MS)
);

INSERT INTO BUSLANES.OSM_IMPORT_SETTINGS (ID)
VALUES (1)
ON CONFLICT (ID) DO NOTHING;

ALTER TABLE BUSLANES.OSM_CITY_UPDATE_RUNS
    ADD COLUMN IF NOT EXISTS ADMINISTRATIVE_PLACES INTEGER NOT NULL DEFAULT 0
        CHECK (ADMINISTRATIVE_PLACES >= 0),
    ADD COLUMN IF NOT EXISTS DUPLICATE_INDEX_OBJECTS INTEGER NOT NULL DEFAULT 0
        CHECK (DUPLICATE_INDEX_OBJECTS >= 0);

CREATE OR REPLACE FUNCTION BUSLANES.REBUILD_CITY_BOUNDARY_HIERARCHY()
RETURNS VOID
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    UPDATE BUSLANES.CITY_BOUNDARIES
    SET AREA_M2 = ST_AREA(GEOM::GEOGRAPHY);

    UPDATE BUSLANES.CITY_BOUNDARIES AS CHILD
    SET PARENT_ID = (
        SELECT PARENT.ID
        FROM BUSLANES.CITY_BOUNDARIES AS PARENT
        WHERE PARENT.ID <> CHILD.ID
          AND PARENT.GEOM && CHILD.GEOM
          AND PARENT.AREA_M2 > CHILD.AREA_M2
          AND NOT ST_EQUALS(PARENT.GEOM, CHILD.GEOM)
          AND ST_COVERS(PARENT.GEOM, CHILD.GEOM)
        ORDER BY PARENT.AREA_M2, PARENT.ID
        LIMIT 1
    );
END
$FUNCTION$;

CREATE OR REPLACE FUNCTION BUSLANES.SYNC_ACTIVE_BOUNDARY_CITIES()
RETURNS VOID
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    -- If an active boundary identity changes, release its stale application
    -- city link so the normalized type/name can be resolved again.
    UPDATE BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    SET CITY_ID = NULL,
        UPDATED_AT = NOW()
    FROM BUSLANES.CITIES AS CITY
    WHERE BOUNDARY.IS_ACTIVE
      AND BOUNDARY.CITY_ID = CITY.ID
      AND (
        LOWER(REGEXP_REPLACE(CITY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
            <> LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
        OR LOWER(REGEXP_REPLACE(CITY.NAME, '[[:space:]]+', '', 'g'))
            <> LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_NAME, '[[:space:]]+', '', 'g'))
      );

    -- CITIES is storage, not the uniqueness authority. Reuse the oldest
    -- compatible row if legacy data contains equivalent normalized identities.
    UPDATE BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    SET CITY_ID = (
            SELECT CITY.ID
            FROM BUSLANES.CITIES AS CITY
            WHERE LOWER(REGEXP_REPLACE(CITY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
                  = LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
              AND LOWER(REGEXP_REPLACE(CITY.NAME, '[[:space:]]+', '', 'g'))
                  = LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_NAME, '[[:space:]]+', '', 'g'))
            ORDER BY CITY.ID
            LIMIT 1
        ),
        UPDATED_AT = NOW()
    WHERE BOUNDARY.IS_ACTIVE
      AND BOUNDARY.CITY_ID IS NULL
      AND EXISTS (
            SELECT 1
            FROM BUSLANES.CITIES AS CITY
            WHERE LOWER(REGEXP_REPLACE(CITY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
                  = LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
              AND LOWER(REGEXP_REPLACE(CITY.NAME, '[[:space:]]+', '', 'g'))
                  = LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_NAME, '[[:space:]]+', '', 'g'))
        );

    INSERT INTO BUSLANES.CITIES (
        SLUG,
        NAME,
        FULL_NAME,
        DISPLAY_TYPE,
        LANE_LENGTH_M,
        ATTRIBUTES
    )
    SELECT
        'osm-' || BOUNDARY.OSM_TYPE || '-' || BOUNDARY.OSM_ID,
        BOUNDARY.DISPLAY_NAME,
        BOUNDARY.DISPLAY_NAME,
        BOUNDARY.DISPLAY_TYPE,
        0,
        JSONB_BUILD_OBJECT(
            '_osm',
            JSONB_BUILD_OBJECT(
                'osmType', BOUNDARY.OSM_TYPE,
                'osmId', BOUNDARY.OSM_ID,
                'placeType', BOUNDARY.PLACE_TYPE,
                'adminLevel', BOUNDARY.ADMIN_LEVEL
            )
        )
    FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    WHERE BOUNDARY.IS_ACTIVE
      AND BOUNDARY.CITY_ID IS NULL
    ON CONFLICT (SLUG) DO UPDATE SET
        NAME = EXCLUDED.NAME,
        FULL_NAME = EXCLUDED.FULL_NAME,
        DISPLAY_TYPE = EXCLUDED.DISPLAY_TYPE,
        ATTRIBUTES = BUSLANES.CITIES.ATTRIBUTES || EXCLUDED.ATTRIBUTES,
        UPDATED_AT = NOW();

    UPDATE BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    SET CITY_ID = CITY.ID,
        UPDATED_AT = NOW()
    FROM BUSLANES.CITIES AS CITY
    WHERE BOUNDARY.IS_ACTIVE
      AND BOUNDARY.CITY_ID IS NULL
      AND CITY.SLUG = 'osm-' || BOUNDARY.OSM_TYPE || '-' || BOUNDARY.OSM_ID;

    UPDATE BUSLANES.CITIES AS CITY
    SET NAME = BOUNDARY.DISPLAY_NAME,
        FULL_NAME = BOUNDARY.DISPLAY_NAME,
        DISPLAY_TYPE = BOUNDARY.DISPLAY_TYPE,
        ATTRIBUTES = CITY.ATTRIBUTES || JSONB_BUILD_OBJECT(
            '_osm',
            JSONB_BUILD_OBJECT(
                'osmType', BOUNDARY.OSM_TYPE,
                'osmId', BOUNDARY.OSM_ID,
                'placeType', BOUNDARY.PLACE_TYPE,
                'adminLevel', BOUNDARY.ADMIN_LEVEL
            )
        ),
        UPDATED_AT = NOW()
    FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    WHERE BOUNDARY.CITY_ID = CITY.ID
      AND BOUNDARY.IS_ACTIVE;

    -- Line rows carry both boundary_id and city_id; keep city_id aligned after
    -- an active boundary is renamed or reassigned.
    UPDATE BUSLANES.CITY_GEOMETRIES AS GEOMETRY
    SET CITY_ID = BOUNDARY.CITY_ID
    FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    WHERE GEOMETRY.BOUNDARY_ID = BOUNDARY.ID
      AND BOUNDARY.IS_ACTIVE
      AND BOUNDARY.CITY_ID IS NOT NULL
      AND GEOMETRY.CITY_ID IS DISTINCT FROM BOUNDARY.CITY_ID;
END
$FUNCTION$;

SELECT BUSLANES.REBUILD_CITY_BOUNDARY_HIERARCHY();
SELECT BUSLANES.SYNC_ACTIVE_BOUNDARY_CITIES();

COMMENT ON COLUMN BUSLANES.CITY_BOUNDARIES.IS_ACTIVE IS
    'Whether this exact OSM object participates in population/line matching and public city reporting.';
COMMENT ON COLUMN BUSLANES.CITY_BOUNDARIES.DISPLAY_NAME IS
    'Administrator-controlled application name; source OSM name remains in OSM_NAME/TAGS.';
COMMENT ON COLUMN BUSLANES.CITY_BOUNDARIES.DISPLAY_TYPE IS
    'Administrator-controlled type used together with DISPLAY_NAME as active application identity.';
COMMENT ON COLUMN BUSLANES.CITY_BOUNDARIES.PARENT_ID IS
    'Smallest strictly larger imported polygon that fully covers this polygon; intersections alone do not create hierarchy.';
COMMENT ON TABLE BUSLANES.OSM_IMPORT_SETTINGS IS
    'DB-backed OSM import selection, batching, timeout and retry settings. Allowed hosts/URLs remain deployment security configuration.';
