ALTER TABLE BUSLANES.OSM_IMPORT_SETTINGS
    ADD COLUMN IF NOT EXISTS MAX_RESPONSE_BYTES BIGINT,
    ADD COLUMN IF NOT EXISTS MAX_TOTAL_BYTES BIGINT;

UPDATE BUSLANES.OSM_IMPORT_SETTINGS
SET MAX_RESPONSE_BYTES = COALESCE(
        MAX_RESPONSE_BYTES,
        LEAST(MAX_BYTES, 134217728)
    ),
    MAX_TOTAL_BYTES = COALESCE(
        MAX_TOTAL_BYTES,
        GREATEST(MAX_BYTES, 2147483648)
    );

ALTER TABLE BUSLANES.OSM_IMPORT_SETTINGS
    ALTER COLUMN MAX_RESPONSE_BYTES SET DEFAULT 134217728,
    ALTER COLUMN MAX_RESPONSE_BYTES SET NOT NULL,
    ALTER COLUMN MAX_TOTAL_BYTES SET DEFAULT 2147483648,
    ALTER COLUMN MAX_TOTAL_BYTES SET NOT NULL;

ALTER TABLE BUSLANES.OSM_IMPORT_SETTINGS
    DROP CONSTRAINT IF EXISTS OSM_IMPORT_SETTINGS_MAX_RESPONSE_BYTES_RANGE,
    DROP CONSTRAINT IF EXISTS OSM_IMPORT_SETTINGS_MAX_TOTAL_BYTES_RANGE;

ALTER TABLE BUSLANES.OSM_IMPORT_SETTINGS
    ADD CONSTRAINT OSM_IMPORT_SETTINGS_MAX_RESPONSE_BYTES_RANGE
        CHECK (MAX_RESPONSE_BYTES BETWEEN 1048576 AND 536870912),
    ADD CONSTRAINT OSM_IMPORT_SETTINGS_MAX_TOTAL_BYTES_RANGE
        CHECK (MAX_TOTAL_BYTES BETWEEN 1048576 AND 8589934592),
    ADD CONSTRAINT OSM_IMPORT_SETTINGS_SIZE_LIMIT_RANGE
        CHECK (MAX_RESPONSE_BYTES <= MAX_TOTAL_BYTES);

COMMENT ON COLUMN BUSLANES.OSM_IMPORT_SETTINGS.MAX_RESPONSE_BYTES IS
    'Maximum bytes buffered for one Overpass response. Oversized geometry batches are split and retried.';
COMMENT ON COLUMN BUSLANES.OSM_IMPORT_SETTINGS.MAX_TOTAL_BYTES IS
    'Maximum cumulative bytes accepted/downloaded by one OSM update operation.';
COMMENT ON COLUMN BUSLANES.OSM_IMPORT_SETTINGS.MAX_BYTES IS
    'Legacy V027 combined size limit retained for migration/backward compatibility; new code uses MAX_RESPONSE_BYTES and MAX_TOTAL_BYTES.';
