SET SEARCH_PATH = BUSLANES, PUBLIC;

CREATE TABLE BUSLANES.OSM_CITY_UPDATE_CHECKPOINTS
(
    ID                      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STATUS                  TEXT        NOT NULL DEFAULT 'downloading',
    SOURCE_URL              TEXT        NOT NULL,
    SETTINGS_FINGERPRINT    TEXT        NOT NULL,
    INDEX_FINGERPRINT       TEXT        NOT NULL,
    OPTIONS                 JSONB       NOT NULL,
    INDEX_OBJECTS           JSONB       NOT NULL,
    SOURCE_ELEMENTS         INTEGER     NOT NULL DEFAULT 0 CHECK (SOURCE_ELEMENTS >= 0),
    DUPLICATE_INDEX_OBJECTS INTEGER     NOT NULL DEFAULT 0 CHECK (DUPLICATE_INDEX_OBJECTS >= 0),
    OSM_TIMESTAMP           TIMESTAMPTZ,
    DOWNLOADED_BYTES        BIGINT      NOT NULL DEFAULT 0 CHECK (DOWNLOADED_BYTES >= 0),
    REQUEST_ATTEMPT_COUNT   INTEGER     NOT NULL DEFAULT 0 CHECK (REQUEST_ATTEMPT_COUNT >= 0),
    RETRY_COUNT             INTEGER     NOT NULL DEFAULT 0 CHECK (RETRY_COUNT >= 0),
    RETRY_WAIT_MS           BIGINT      NOT NULL DEFAULT 0 CHECK (RETRY_WAIT_MS >= 0),
    THROTTLE_WAIT_MS        BIGINT      NOT NULL DEFAULT 0 CHECK (THROTTLE_WAIT_MS >= 0),
    IGNORED_ELEMENTS        INTEGER     NOT NULL DEFAULT 0 CHECK (IGNORED_ELEMENTS >= 0),
    LAST_ERROR              JSONB,
    CREATED_AT              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    COMPLETED_AT            TIMESTAMPTZ,
    CONSTRAINT OSM_CITY_UPDATE_CHECKPOINTS_STATUS_CHECK CHECK (
        STATUS IN ('downloading', 'failed', 'cancelled', 'ready', 'completed', 'discarded')
    ),
    CONSTRAINT OSM_CITY_UPDATE_CHECKPOINTS_OPTIONS_OBJECT_CHECK CHECK (
        JSONB_TYPEOF(OPTIONS) = 'object'
    ),
    CONSTRAINT OSM_CITY_UPDATE_CHECKPOINTS_INDEX_ARRAY_CHECK CHECK (
        JSONB_TYPEOF(INDEX_OBJECTS) = 'array'
    )
);

CREATE UNIQUE INDEX OSM_CITY_UPDATE_CHECKPOINTS_ONE_RESUMABLE_UDX
    ON BUSLANES.OSM_CITY_UPDATE_CHECKPOINTS ((1))
    WHERE STATUS IN ('downloading', 'failed', 'cancelled', 'ready');

CREATE INDEX OSM_CITY_UPDATE_CHECKPOINTS_UPDATED_IDX
    ON BUSLANES.OSM_CITY_UPDATE_CHECKPOINTS (UPDATED_AT DESC, ID DESC);

CREATE TABLE BUSLANES.OSM_CITY_UPDATE_CHECKPOINT_STAGE
(
    CHECKPOINT_ID    BIGINT      NOT NULL
        REFERENCES BUSLANES.OSM_CITY_UPDATE_CHECKPOINTS (ID) ON DELETE CASCADE,
    OSM_TYPE         TEXT        NOT NULL,
    OSM_ID           BIGINT      NOT NULL,
    NAME             TEXT        NOT NULL,
    PLACE_TYPE       TEXT,
    ADMIN_LEVEL       SMALLINT,
    TAGS              JSONB       NOT NULL,
    GEOM              GEOMETRY(MULTIPOLYGON, 4326) NOT NULL,
    BOUNDS            GEOMETRY(POLYGON, 4326) NOT NULL,
    CONTENT_CHECKSUM  TEXT        NOT NULL,
    STAGED_AT         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (CHECKPOINT_ID, OSM_TYPE, OSM_ID)
);

CREATE INDEX OSM_CITY_UPDATE_CHECKPOINT_STAGE_GEOM_IDX
    ON BUSLANES.OSM_CITY_UPDATE_CHECKPOINT_STAGE USING GIST (GEOM);

COMMENT ON TABLE BUSLANES.OSM_CITY_UPDATE_CHECKPOINTS IS
    'Durable OSM import work snapshot. Resumable rows survive task failure and Node restart; production boundaries are not modified until final commit.';
COMMENT ON COLUMN BUSLANES.OSM_CITY_UPDATE_CHECKPOINTS.SETTINGS_FINGERPRINT IS
    'SHA-256 of source/selectors/query/batch semantics that must match before resume.';
COMMENT ON COLUMN BUSLANES.OSM_CITY_UPDATE_CHECKPOINTS.INDEX_FINGERPRINT IS
    'SHA-256 of the exact ordered OSM object index captured for this work snapshot.';
COMMENT ON COLUMN BUSLANES.OSM_CITY_UPDATE_CHECKPOINTS.INDEX_OBJECTS IS
    'Exact ordered OSM type/id index used for resume without re-querying Overpass.';
COMMENT ON TABLE BUSLANES.OSM_CITY_UPDATE_CHECKPOINT_STAGE IS
    'Durable validated OSM geometries staged per checkpoint; rows are deleted only after successful final commit or explicit discard.';
