SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.OSM_CITY_UPDATE_CHECKPOINTS
    ADD COLUMN IF NOT EXISTS STAGED_BATCH_COUNT INTEGER NOT NULL DEFAULT 0
        CHECK (STAGED_BATCH_COUNT >= 0);

COMMENT ON COLUMN BUSLANES.OSM_CITY_UPDATE_CHECKPOINTS.STAGED_BATCH_COUNT IS
    'Cumulative number of successfully persisted geometry batches across the original run and all resume attempts.';
