SET SEARCH_PATH = BUSLANES, PUBLIC;

-- Territory data belongs to the exact OSM boundary, independently from
-- whether that boundary participates in public/report calculations.
ALTER TABLE BUSLANES.CITY_BOUNDARIES
    ADD COLUMN IF NOT EXISTS POPULATION INTEGER
        CHECK (POPULATION IS NULL OR POPULATION > 0),
    ADD COLUMN IF NOT EXISTS POPULATION_AS_OF DATE,
    ADD COLUMN IF NOT EXISTS POPULATION_SOURCE TEXT,
    ADD COLUMN IF NOT EXISTS ATTRIBUTES JSONB NOT NULL DEFAULT '{}'::JSONB
        CHECK (JSONB_TYPEOF(ATTRIBUTES) = 'object');

-- Preserve the existing population dataset by attaching each current city
-- population to its active exact OSM boundary.
UPDATE BUSLANES.CITY_BOUNDARIES AS BOUNDARY
SET POPULATION = POPULATION_DATA.POPULATION,
    POPULATION_AS_OF = POPULATION_DATA.AS_OF,
    POPULATION_SOURCE = POPULATION_DATA.SOURCE,
    ATTRIBUTES = POPULATION_DATA.ATTRIBUTES
FROM BUSLANES.CITY_POPULATIONS AS POPULATION_DATA
WHERE BOUNDARY.IS_ACTIVE
  AND BOUNDARY.CITY_ID = POPULATION_DATA.CITY_ID
  AND BOUNDARY.POPULATION IS NULL;

CREATE OR REPLACE FUNCTION BUSLANES.SYNC_ACTIVE_BOUNDARY_POPULATIONS()
RETURNS VOID
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    INSERT INTO BUSLANES.CITY_POPULATIONS (
        CITY_ID,
        POPULATION,
        AS_OF,
        SOURCE,
        ATTRIBUTES,
        UPDATED_AT
    )
    SELECT
        BOUNDARY.CITY_ID,
        BOUNDARY.POPULATION,
        BOUNDARY.POPULATION_AS_OF,
        BOUNDARY.POPULATION_SOURCE,
        BOUNDARY.ATTRIBUTES,
        NOW()
    FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    WHERE BOUNDARY.IS_ACTIVE
      AND BOUNDARY.CITY_ID IS NOT NULL
      AND BOUNDARY.POPULATION IS NOT NULL
    ON CONFLICT (CITY_ID) DO UPDATE SET
        POPULATION = EXCLUDED.POPULATION,
        AS_OF = EXCLUDED.AS_OF,
        SOURCE = EXCLUDED.SOURCE,
        ATTRIBUTES = EXCLUDED.ATTRIBUTES,
        UPDATED_AT = NOW();

    DELETE FROM BUSLANES.CITY_POPULATIONS AS POPULATION_DATA
    USING BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    WHERE BOUNDARY.IS_ACTIVE
      AND BOUNDARY.CITY_ID = POPULATION_DATA.CITY_ID
      AND BOUNDARY.POPULATION IS NULL;
END
$FUNCTION$;

SELECT BUSLANES.SYNC_ACTIVE_BOUNDARY_POPULATIONS();

COMMENT ON COLUMN BUSLANES.CITY_BOUNDARIES.POPULATION IS
    'Population attached to this exact OSM territory; independent from IS_ACTIVE.';
COMMENT ON COLUMN BUSLANES.CITY_BOUNDARIES.POPULATION_AS_OF IS
    'Observation date for territory population; independent from IS_ACTIVE.';
COMMENT ON COLUMN BUSLANES.CITY_BOUNDARIES.POPULATION_SOURCE IS
    'Population source for this exact OSM territory.';
COMMENT ON COLUMN BUSLANES.CITY_BOUNDARIES.ATTRIBUTES IS
    'Administrator/imported attributes for this exact OSM territory; independent from IS_ACTIVE.';
COMMENT ON FUNCTION BUSLANES.SYNC_ACTIVE_BOUNDARY_POPULATIONS() IS
    'Projects data from active exact OSM boundaries into CITY_POPULATIONS used by reports/public output.';
