SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    DROP CONSTRAINT IF EXISTS CITY_GEOMETRIES_LINEAR,
    DROP CONSTRAINT IF EXISTS CITY_GEOMETRIES_DIRECTION_MULTIPLIER,
    DROP CONSTRAINT IF EXISTS CITY_GEOMETRIES_LANES_CHECK;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ALTER COLUMN LANES DROP NOT NULL,
    ALTER COLUMN LINE_TYPE_ID DROP NOT NULL,
    ALTER COLUMN LENGTH_M DROP NOT NULL,
    ALTER COLUMN LANE_LENGTH_M DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS DISPLAY_NAME TEXT,
    ADD COLUMN IF NOT EXISTS TOOLTIP TEXT,
    ADD COLUMN IF NOT EXISTS TAGS TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
    ADD COLUMN IF NOT EXISTS SOURCE_TAGS JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS IS_VISIBLE BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS WAS_EDITED BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW();

UPDATE BUSLANES.CITY_GEOMETRIES
SET DISPLAY_NAME = NULLIF(BTRIM(PROPERTIES ->> 'placemarkName'), ''),
    SOURCE_TAGS = CASE
        WHEN PROPERTIES ->> 'source' = 'kml'
            THEN PROPERTIES - 'fingerprint'
        ELSE '{}'::JSONB
    END
WHERE DISPLAY_NAME IS NULL
   OR SOURCE_TAGS = '{}'::JSONB;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ADD CONSTRAINT CITY_GEOMETRIES_SUPPORTED_TYPE CHECK (
        GEOMETRYTYPE(GEOM) IN (
            'POINT',
            'LINESTRING',
            'MULTILINESTRING',
            'POLYGON',
            'MULTIPOLYGON'
        )
    ),
    ADD CONSTRAINT CITY_GEOMETRIES_LINE_STATE CHECK (
        (
            GEOMETRYTYPE(GEOM) IN ('LINESTRING', 'MULTILINESTRING')
            AND LINE_TYPE_ID IS NOT NULL
            AND LANES IN (1, 2)
            AND LENGTH_M IS NOT NULL
            AND LANE_LENGTH_M IS NOT NULL
        )
        OR
        (
            GEOMETRYTYPE(GEOM) IN ('POINT', 'POLYGON', 'MULTIPOLYGON')
            AND LINE_TYPE_ID IS NULL
            AND LANES IS NULL
            AND LENGTH_M IS NULL
            AND LANE_LENGTH_M IS NULL
        )
    ),
    ADD CONSTRAINT CITY_GEOMETRIES_DISPLAY_NAME_LENGTH CHECK (
        DISPLAY_NAME IS NULL OR CHAR_LENGTH(DISPLAY_NAME) <= 240
    ),
    ADD CONSTRAINT CITY_GEOMETRIES_TOOLTIP_LENGTH CHECK (
        TOOLTIP IS NULL OR CHAR_LENGTH(TOOLTIP) <= 2000
    ),
    ADD CONSTRAINT CITY_GEOMETRIES_TAG_COUNT CHECK (
        CARDINALITY(TAGS) <= 64
    ),
    ADD CONSTRAINT CITY_GEOMETRIES_SOURCE_TAGS_OBJECT CHECK (
        JSONB_TYPEOF(SOURCE_TAGS) = 'object'
    );

CREATE INDEX IF NOT EXISTS CITY_GEOMETRIES_TAGS_GIN_IDX
    ON BUSLANES.CITY_GEOMETRIES USING GIN (TAGS);

CREATE INDEX IF NOT EXISTS CITY_GEOMETRIES_VISIBLE_CITY_IDX
    ON BUSLANES.CITY_GEOMETRIES (CITY_ID, ID)
    WHERE IS_VISIBLE;

COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.DISPLAY_NAME IS
    'Administrator-managed display name. Empty names are rendered with a generated type/id label.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.TOOLTIP IS
    'Optional hover/popup text; an empty value falls back to DISPLAY_NAME.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.TAGS IS
    'Administrator-managed business tags used by report metric filters.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.SOURCE_TAGS IS
    'Source metadata retained separately from editable business tags for import conflict matching.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.IS_VISIBLE IS
    'Controls public-map visibility only; hidden geometries still participate in metrics.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.WAS_EDITED IS
    'Sticky flag set by any manual editor mutation; no attempt is made to detect a return to source state.';
