SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.ADMIN_SECURITY_SETTINGS
    ADD COLUMN IF NOT EXISTS PASSWORD_MIN_LENGTH INTEGER NOT NULL DEFAULT 12,
    ADD COLUMN IF NOT EXISTS PASSWORD_MAX_LENGTH INTEGER NOT NULL DEFAULT 1024,
    ADD COLUMN IF NOT EXISTS PASSWORD_REQUIRE_LOWERCASE BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS PASSWORD_REQUIRE_UPPERCASE BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS PASSWORD_REQUIRE_DIGIT BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS PASSWORD_REQUIRE_SPECIAL BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE BUSLANES.ADMIN_SECURITY_SETTINGS
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_PASSWORD_MIN_LENGTH_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_PASSWORD_MIN_LENGTH_CHECK CHECK (
        PASSWORD_MIN_LENGTH BETWEEN 1 AND 4096
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_PASSWORD_MAX_LENGTH_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_PASSWORD_MAX_LENGTH_CHECK CHECK (
        PASSWORD_MAX_LENGTH BETWEEN 1 AND 4096
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_PASSWORD_LENGTH_RANGE_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_PASSWORD_LENGTH_RANGE_CHECK CHECK (
        PASSWORD_MIN_LENGTH <= PASSWORD_MAX_LENGTH
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_PASSWORD_REQUIRED_CLASSES_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_PASSWORD_REQUIRED_CLASSES_CHECK CHECK (
        PASSWORD_MAX_LENGTH >=
            PASSWORD_REQUIRE_LOWERCASE::INTEGER +
            PASSWORD_REQUIRE_UPPERCASE::INTEGER +
            PASSWORD_REQUIRE_DIGIT::INTEGER +
            PASSWORD_REQUIRE_SPECIAL::INTEGER
    );

COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.PASSWORD_MIN_LENGTH IS
    'Minimum administrator password length.';
COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.PASSWORD_MAX_LENGTH IS
    'Maximum administrator password length.';
COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.PASSWORD_REQUIRE_LOWERCASE IS
    'Require at least one Unicode lowercase letter.';
COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.PASSWORD_REQUIRE_UPPERCASE IS
    'Require at least one Unicode uppercase letter.';
COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.PASSWORD_REQUIRE_DIGIT IS
    'Require at least one Unicode numeric character.';
COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.PASSWORD_REQUIRE_SPECIAL IS
    'Require at least one character that is neither a Unicode letter nor a number.';
