SET SEARCH_PATH = BUSLANES, PUBLIC;

CREATE TABLE IF NOT EXISTS BUSLANES.GEOMETRY_IMPORT_SESSIONS
(
    ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    KIND       TEXT        NOT NULL CHECK (KIND IN ('kml')),
    STATUS     TEXT        NOT NULL DEFAULT 'pending'
                           CHECK (STATUS IN ('pending', 'applied')),
    METADATA   JSONB       NOT NULL DEFAULT '{}'::JSONB
                           CHECK (JSONB_TYPEOF(METADATA) = 'object'),
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS GEOMETRY_IMPORT_ONE_PENDING_UIDX
    ON BUSLANES.GEOMETRY_IMPORT_SESSIONS ((STATUS))
    WHERE STATUS = 'pending';

CREATE TABLE IF NOT EXISTS BUSLANES.GEOMETRY_IMPORT_STAGE
(
    ID               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SESSION_ID       BIGINT      NOT NULL
                                 REFERENCES BUSLANES.GEOMETRY_IMPORT_SESSIONS (ID)
                                 ON DELETE CASCADE,
    SEQ              INTEGER     NOT NULL CHECK (SEQ >= 0),
    CITY_ID          BIGINT      REFERENCES BUSLANES.CITIES (ID) ON DELETE SET NULL,
    BOUNDARY_ID      BIGINT      NOT NULL
                                 REFERENCES BUSLANES.CITY_BOUNDARIES (ID) ON DELETE RESTRICT,
    LINE_TYPE_ID     BIGINT      REFERENCES BUSLANES.LINE_TYPES (ID) ON DELETE RESTRICT,
    LINE_TYPE_NAME   TEXT        NOT NULL,
    LANES            SMALLINT    NOT NULL CHECK (LANES IN (1, 2)),
    DISPLAY_NAME     TEXT,
    PROPERTIES       JSONB       NOT NULL DEFAULT '{}'::JSONB,
    SOURCE_TAGS      JSONB       NOT NULL DEFAULT '{}'::JSONB
                                 CHECK (JSONB_TYPEOF(SOURCE_TAGS) = 'object'),
    GEOM             PUBLIC.GEOMETRY(Geometry, 4326) NOT NULL,
    AUTO_EXISTING_ID BIGINT      REFERENCES BUSLANES.CITY_GEOMETRIES (ID) ON DELETE SET NULL,
    CONSTRAINT GEOMETRY_IMPORT_STAGE_LINEAR CHECK (
        GEOMETRYTYPE(GEOM) IN ('LINESTRING', 'MULTILINESTRING')
    ),
    CONSTRAINT GEOMETRY_IMPORT_STAGE_VALID CHECK (ST_ISVALID(GEOM)),
    CONSTRAINT GEOMETRY_IMPORT_STAGE_SESSION_SEQ UNIQUE (SESSION_ID, SEQ)
);

CREATE INDEX IF NOT EXISTS GEOMETRY_IMPORT_STAGE_SESSION_IDX
    ON BUSLANES.GEOMETRY_IMPORT_STAGE (SESSION_ID, ID);
CREATE INDEX IF NOT EXISTS GEOMETRY_IMPORT_STAGE_GEOM_GIST_IDX
    ON BUSLANES.GEOMETRY_IMPORT_STAGE USING GIST (GEOM);

CREATE TABLE IF NOT EXISTS BUSLANES.GEOMETRY_IMPORT_CONFLICTS
(
    ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SESSION_ID  BIGINT NOT NULL
                       REFERENCES BUSLANES.GEOMETRY_IMPORT_SESSIONS (ID)
                       ON DELETE CASCADE,
    INCOMING_ID BIGINT NOT NULL
                       REFERENCES BUSLANES.GEOMETRY_IMPORT_STAGE (ID)
                       ON DELETE CASCADE,
    EXISTING_ID BIGINT
                       REFERENCES BUSLANES.CITY_GEOMETRIES (ID)
                       ON DELETE SET NULL,
    RELATION    TEXT NOT NULL CHECK (
        RELATION IN ('equals-different-tags', 'within-same-tags', 'overlaps')
    ),
    CONSTRAINT GEOMETRY_IMPORT_CONFLICT_PAIR UNIQUE (
        SESSION_ID, INCOMING_ID, EXISTING_ID
    )
);

CREATE INDEX IF NOT EXISTS GEOMETRY_IMPORT_CONFLICT_SESSION_IDX
    ON BUSLANES.GEOMETRY_IMPORT_CONFLICTS (SESSION_ID, INCOMING_ID);

COMMENT ON TABLE BUSLANES.GEOMETRY_IMPORT_SESSIONS IS
    'Durable staging sessions for legacy geometry imports that need administrator conflict resolution before production data changes.';
COMMENT ON COLUMN BUSLANES.GEOMETRY_IMPORT_STAGE.AUTO_EXISTING_ID IS
    'Exact ST_Equals + identical SOURCE_TAGS match. It is not a conflict and may be refreshed automatically.';
COMMENT ON TABLE BUSLANES.GEOMETRY_IMPORT_CONFLICTS IS
    'Potential semantic conflicts found only by explicit PostGIS relations; the administrator chooses the correct result visually.';
