SET SEARCH_PATH = BUSLANES, PUBLIC;

-- CITY_ID is the semantic owner of every project geometry. BOUNDARY_ID is an
-- optional OSM/matching link and must never decide whether the geometry exists
-- in metrics or on the public map.
SELECT BUSLANES.SYNC_ACTIVE_BOUNDARY_CITIES();

UPDATE BUSLANES.CITY_GEOMETRIES AS GEOMETRY
SET CITY_ID = BOUNDARY.CITY_ID,
    UPDATED_AT = NOW()
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
WHERE GEOMETRY.BOUNDARY_ID = BOUNDARY.ID
  AND BOUNDARY.IS_ACTIVE
  AND BOUNDARY.CITY_ID IS NOT NULL
  AND GEOMETRY.CITY_ID IS DISTINCT FROM BOUNDARY.CITY_ID;

DO $MIGRATION$
DECLARE
    ORPHAN_COUNT BIGINT;
BEGIN
    SELECT COUNT(*)
    INTO ORPHAN_COUNT
    FROM BUSLANES.CITY_GEOMETRIES
    WHERE CITY_ID IS NULL;

    IF ORPHAN_COUNT > 0 THEN
        RAISE EXCEPTION
            'Cannot enforce geometry ownership: % CITY_GEOMETRIES rows have no CITY_ID after active-boundary repair',
            ORPHAN_COUNT;
    END IF;
END
$MIGRATION$;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ALTER COLUMN CITY_ID SET NOT NULL;

CREATE OR REPLACE FUNCTION BUSLANES.NORMALIZE_CITY_GEOMETRY_DERIVED()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    IF GEOMETRYTYPE(NEW.GEOM) IN ('LINESTRING', 'MULTILINESTRING') THEN
        NEW.LENGTH_M := ST_LENGTH(NEW.GEOM::GEOGRAPHY);
        NEW.LANE_LENGTH_M := NEW.LENGTH_M * NEW.LANES;
    ELSE
        NEW.LENGTH_M := NULL;
        NEW.LANE_LENGTH_M := NULL;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        NEW.UPDATED_AT := NOW();
    END IF;

    RETURN NEW;
END
$FUNCTION$;

DROP TRIGGER IF EXISTS CITY_GEOMETRIES_NORMALIZE_DERIVED
    ON BUSLANES.CITY_GEOMETRIES;
CREATE TRIGGER CITY_GEOMETRIES_NORMALIZE_DERIVED
BEFORE INSERT OR UPDATE
ON BUSLANES.CITY_GEOMETRIES
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.NORMALIZE_CITY_GEOMETRY_DERIVED();

CREATE OR REPLACE FUNCTION BUSLANES.ALIGN_ACTIVE_BOUNDARY_GEOMETRIES()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    IF NEW.IS_ACTIVE AND NEW.CITY_ID IS NOT NULL THEN
        UPDATE BUSLANES.CITY_GEOMETRIES AS GEOMETRY
        SET CITY_ID = NEW.CITY_ID
        WHERE GEOMETRY.BOUNDARY_ID = NEW.ID
          AND GEOMETRY.CITY_ID IS DISTINCT FROM NEW.CITY_ID;
    END IF;
    RETURN NEW;
END
$FUNCTION$;

DROP TRIGGER IF EXISTS CITY_BOUNDARIES_ALIGN_GEOMETRIES
    ON BUSLANES.CITY_BOUNDARIES;
CREATE TRIGGER CITY_BOUNDARIES_ALIGN_GEOMETRIES
AFTER INSERT OR UPDATE
ON BUSLANES.CITY_BOUNDARIES
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.ALIGN_ACTIVE_BOUNDARY_GEOMETRIES();

CREATE OR REPLACE FUNCTION BUSLANES.VALIDATE_ACTIVE_BOUNDARY_CONSISTENCY()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    IF NEW.IS_ACTIVE AND NEW.CITY_ID IS NULL THEN
        RAISE EXCEPTION
            'Active CITY_BOUNDARIES row % (%) has no CITY_ID',
            NEW.ID,
            NEW.OSM_TYPE || '/' || NEW.OSM_ID;
    END IF;

    IF NEW.IS_ACTIVE AND EXISTS (
        SELECT 1
        FROM BUSLANES.CITY_GEOMETRIES AS GEOMETRY
        WHERE GEOMETRY.BOUNDARY_ID = NEW.ID
          AND GEOMETRY.CITY_ID IS DISTINCT FROM NEW.CITY_ID
    ) THEN
        RAISE EXCEPTION
            'Active boundary % has CITY_GEOMETRIES rows linked to another city',
            NEW.ID;
    END IF;

    RETURN NULL;
END
$FUNCTION$;

DROP TRIGGER IF EXISTS CITY_BOUNDARIES_CONSISTENCY_CHECK
    ON BUSLANES.CITY_BOUNDARIES;
CREATE CONSTRAINT TRIGGER CITY_BOUNDARIES_CONSISTENCY_CHECK
AFTER INSERT OR UPDATE
ON BUSLANES.CITY_BOUNDARIES
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.VALIDATE_ACTIVE_BOUNDARY_CONSISTENCY();

CREATE OR REPLACE FUNCTION BUSLANES.VALIDATE_CITY_GEOMETRY_CONSISTENCY()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    BOUNDARY_ACTIVE BOOLEAN;
    BOUNDARY_CITY_ID BIGINT;
BEGIN
    IF NEW.BOUNDARY_ID IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT BOUNDARY.IS_ACTIVE, BOUNDARY.CITY_ID
    INTO BOUNDARY_ACTIVE, BOUNDARY_CITY_ID
    FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    WHERE BOUNDARY.ID = NEW.BOUNDARY_ID;

    IF BOUNDARY_ACTIVE
       AND (
           BOUNDARY_CITY_ID IS NULL
           OR NEW.CITY_ID IS DISTINCT FROM BOUNDARY_CITY_ID
       ) THEN
        RAISE EXCEPTION
            'CITY_GEOMETRIES row % has CITY_ID %, but active boundary % belongs to CITY_ID %',
            NEW.ID,
            NEW.CITY_ID,
            NEW.BOUNDARY_ID,
            BOUNDARY_CITY_ID;
    END IF;

    RETURN NULL;
END
$FUNCTION$;

DROP TRIGGER IF EXISTS CITY_GEOMETRIES_CONSISTENCY_CHECK
    ON BUSLANES.CITY_GEOMETRIES;
CREATE CONSTRAINT TRIGGER CITY_GEOMETRIES_CONSISTENCY_CHECK
AFTER INSERT OR UPDATE
ON BUSLANES.CITY_GEOMETRIES
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.VALIDATE_CITY_GEOMETRY_CONSISTENCY();

CREATE OR REPLACE FUNCTION BUSLANES.ASSERT_NO_PENDING_GEOMETRY_IMPORT()
RETURNS VOID
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    PENDING_ID BIGINT;
BEGIN
    SELECT ID
    INTO PENDING_ID
    FROM BUSLANES.GEOMETRY_IMPORT_SESSIONS
    WHERE STATUS = 'pending'
    ORDER BY ID
    LIMIT 1;

    IF PENDING_ID IS NOT NULL THEN
        RAISE EXCEPTION
            'Geometry import session % is waiting for administrator conflict resolution',
            PENDING_ID
            USING ERRCODE = '55000';
    END IF;
END
$FUNCTION$;

COMMENT ON FUNCTION BUSLANES.ASSERT_NO_PENDING_GEOMETRY_IMPORT() IS
    'Prevents geometry/boundary mutations from invalidating a durable staged import conflict session.';
