SET SEARCH_PATH = BUSLANES, PUBLIC;

-- CITY_BOUNDARIES and CITY_GEOMETRIES are durable domain data. CITIES is an
-- application identity/materialization layer, therefore deleting a CITIES row
-- must detach dependent records instead of destroying source/manual geometry.
ALTER TABLE BUSLANES.CITY_BOUNDARIES
    DROP CONSTRAINT IF EXISTS CITY_BOUNDARIES_CITY_ID_FKEY;
ALTER TABLE BUSLANES.CITY_BOUNDARIES
    ADD CONSTRAINT CITY_BOUNDARIES_CITY_ID_FKEY
        FOREIGN KEY (CITY_ID)
        REFERENCES BUSLANES.CITIES (ID)
        ON DELETE SET NULL;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    DROP CONSTRAINT IF EXISTS CITY_GEOMETRIES_CITY_ID_FKEY;
ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ADD CONSTRAINT CITY_GEOMETRIES_CITY_ID_FKEY
        FOREIGN KEY (CITY_ID)
        REFERENCES BUSLANES.CITIES (ID)
        ON DELETE SET NULL;

-- BOUNDARY_ID is authoritative when it exists. Repair historical mismatches
-- before installing the automatic guards.
UPDATE BUSLANES.CITY_GEOMETRIES AS GEOMETRY
SET CITY_ID = BOUNDARY.CITY_ID,
    UPDATED_AT = NOW()
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
WHERE GEOMETRY.BOUNDARY_ID = BOUNDARY.ID
  AND GEOMETRY.CITY_ID IS DISTINCT FROM BOUNDARY.CITY_ID;

CREATE OR REPLACE FUNCTION BUSLANES.SYNC_GEOMETRY_CITY_FROM_BOUNDARY()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    BOUNDARY_CITY_ID BIGINT;
BEGIN
    IF NEW.BOUNDARY_ID IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT BOUNDARY.CITY_ID
    INTO BOUNDARY_CITY_ID
    FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    WHERE BOUNDARY.ID = NEW.BOUNDARY_ID;

    IF FOUND THEN
        NEW.CITY_ID := BOUNDARY_CITY_ID;
    END IF;

    RETURN NEW;
END
$FUNCTION$;

DROP TRIGGER IF EXISTS CITY_GEOMETRIES_SYNC_CITY_FROM_BOUNDARY
    ON BUSLANES.CITY_GEOMETRIES;
CREATE TRIGGER CITY_GEOMETRIES_SYNC_CITY_FROM_BOUNDARY
BEFORE INSERT OR UPDATE OF BOUNDARY_ID, CITY_ID
ON BUSLANES.CITY_GEOMETRIES
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.SYNC_GEOMETRY_CITY_FROM_BOUNDARY();

CREATE OR REPLACE FUNCTION BUSLANES.PROPAGATE_BOUNDARY_CITY_TO_GEOMETRIES()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    IF OLD.CITY_ID IS DISTINCT FROM NEW.CITY_ID THEN
        UPDATE BUSLANES.CITY_GEOMETRIES
        SET CITY_ID = NEW.CITY_ID,
            UPDATED_AT = NOW()
        WHERE BOUNDARY_ID = NEW.ID
          AND CITY_ID IS DISTINCT FROM NEW.CITY_ID;
    END IF;
    RETURN NEW;
END
$FUNCTION$;

DROP TRIGGER IF EXISTS CITY_BOUNDARIES_PROPAGATE_CITY_TO_GEOMETRIES
    ON BUSLANES.CITY_BOUNDARIES;
CREATE TRIGGER CITY_BOUNDARIES_PROPAGATE_CITY_TO_GEOMETRIES
AFTER UPDATE OF CITY_ID
ON BUSLANES.CITY_BOUNDARIES
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.PROPAGATE_BOUNDARY_CITY_TO_GEOMETRIES();

-- One canonical definition of a geometry that participates in public output,
-- cached statistics and report metrics. IS_VISIBLE deliberately does not belong
-- here: visibility affects rendering only, not calculations.
CREATE OR REPLACE VIEW BUSLANES.EFFECTIVE_CITY_GEOMETRIES AS
SELECT GEOMETRY.*
FROM BUSLANES.CITY_GEOMETRIES AS GEOMETRY
JOIN BUSLANES.CITY_BOUNDARIES AS BOUNDARY
  ON BOUNDARY.ID = GEOMETRY.BOUNDARY_ID
 AND BOUNDARY.IS_ACTIVE
 AND BOUNDARY.CITY_ID IS NOT NULL
 AND BOUNDARY.CITY_ID = GEOMETRY.CITY_ID;

COMMENT ON VIEW BUSLANES.EFFECTIVE_CITY_GEOMETRIES IS
    'Canonical active geometry set: exact own boundary is active and boundary/city links agree. Hidden rows remain effective for metrics.';

CREATE OR REPLACE FUNCTION BUSLANES.ASSERT_NO_PENDING_GEOMETRY_IMPORT()
RETURNS VOID
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM BUSLANES.GEOMETRY_IMPORT_SESSIONS
        WHERE STATUS = 'pending'
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'A staged geometry import is waiting for administrator conflict resolution';
    END IF;
END
$FUNCTION$;

CREATE OR REPLACE FUNCTION BUSLANES.ASSERT_CITY_GEOMETRY_INVARIANTS()
RETURNS VOID
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    CNT BIGINT;
BEGIN
    SELECT COUNT(*)
    INTO CNT
    FROM BUSLANES.CITY_BOUNDARIES
    WHERE IS_ACTIVE
      AND CITY_ID IS NULL;

    IF CNT > 0 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = FORMAT(
                'Schema invariant violation: %s active city boundaries have no CITY_ID',
                CNT
            );
    END IF;

    SELECT COUNT(*)
    INTO CNT
    FROM BUSLANES.CITY_GEOMETRIES AS GEOMETRY
    JOIN BUSLANES.CITY_BOUNDARIES AS BOUNDARY
      ON BOUNDARY.ID = GEOMETRY.BOUNDARY_ID
    WHERE GEOMETRY.CITY_ID IS DISTINCT FROM BOUNDARY.CITY_ID;

    IF CNT > 0 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = FORMAT(
                'Schema invariant violation: %s geometries disagree with their boundary CITY_ID',
                CNT
            );
    END IF;
END
$FUNCTION$;

-- Repair active city links using the canonical synchronizer, then verify the
-- complete relation before this migration commits.
SELECT BUSLANES.SYNC_ACTIVE_BOUNDARY_CITIES();
SELECT BUSLANES.ASSERT_CITY_GEOMETRY_INVARIANTS();
