SET SEARCH_PATH = BUSLANES, PUBLIC;

SELECT BUSLANES.SYNC_ACTIVE_BOUNDARY_CITIES();

CREATE OR REPLACE FUNCTION BUSLANES.VALIDATE_CITY_BOUNDARY_IDENTITY()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    BAD_BOUNDARY_ID BIGINT;
BEGIN
    SELECT BOUNDARY.ID
    INTO BAD_BOUNDARY_ID
    FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    JOIN BUSLANES.CITIES AS CITY
      ON CITY.ID = BOUNDARY.CITY_ID
    WHERE BOUNDARY.IS_ACTIVE
      AND (
        LOWER(REGEXP_REPLACE(CITY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
          <> LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
        OR LOWER(REGEXP_REPLACE(CITY.NAME, '[[:space:]]+', '', 'g'))
          <> LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_NAME, '[[:space:]]+', '', 'g'))
      )
    LIMIT 1;

    IF BAD_BOUNDARY_ID IS NOT NULL THEN
        RAISE EXCEPTION
            'Active boundary % is linked to a CITIES row with a different normalized identity',
            BAD_BOUNDARY_ID;
    END IF;

    RETURN NULL;
END
$FUNCTION$;

DROP TRIGGER IF EXISTS CITIES_BOUNDARY_IDENTITY_CHECK
    ON BUSLANES.CITIES;
CREATE CONSTRAINT TRIGGER CITIES_BOUNDARY_IDENTITY_CHECK
AFTER INSERT OR UPDATE
ON BUSLANES.CITIES
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.VALIDATE_CITY_BOUNDARY_IDENTITY();

DROP TRIGGER IF EXISTS CITY_BOUNDARIES_IDENTITY_CHECK
    ON BUSLANES.CITY_BOUNDARIES;
CREATE CONSTRAINT TRIGGER CITY_BOUNDARIES_IDENTITY_CHECK
AFTER INSERT OR UPDATE
ON BUSLANES.CITY_BOUNDARIES
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.VALIDATE_CITY_BOUNDARY_IDENTITY();

CREATE OR REPLACE VIEW BUSLANES.GEOMETRY_MODEL_INTEGRITY AS
SELECT
    'active-boundary-without-city'::text AS issue,
    BOUNDARY.ID::bigint AS boundary_id,
    NULL::bigint AS geometry_id,
    BOUNDARY.CITY_ID::bigint AS city_id
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
WHERE BOUNDARY.IS_ACTIVE
  AND BOUNDARY.CITY_ID IS NULL

UNION ALL

SELECT
    'active-boundary-city-identity-mismatch'::text,
    BOUNDARY.ID::bigint,
    NULL::bigint,
    BOUNDARY.CITY_ID::bigint
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
JOIN BUSLANES.CITIES AS CITY ON CITY.ID = BOUNDARY.CITY_ID
WHERE BOUNDARY.IS_ACTIVE
  AND (
    LOWER(REGEXP_REPLACE(CITY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
      <> LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
    OR LOWER(REGEXP_REPLACE(CITY.NAME, '[[:space:]]+', '', 'g'))
      <> LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_NAME, '[[:space:]]+', '', 'g'))
  )

UNION ALL

SELECT
    'geometry-active-boundary-city-mismatch'::text,
    BOUNDARY.ID::bigint,
    GEOMETRY.ID::bigint,
    GEOMETRY.CITY_ID::bigint
FROM BUSLANES.CITY_GEOMETRIES AS GEOMETRY
JOIN BUSLANES.CITY_BOUNDARIES AS BOUNDARY ON BOUNDARY.ID = GEOMETRY.BOUNDARY_ID
WHERE BOUNDARY.IS_ACTIVE
  AND GEOMETRY.CITY_ID IS DISTINCT FROM BOUNDARY.CITY_ID

UNION ALL

SELECT
    'geometry-derived-line-value-mismatch'::text,
    GEOMETRY.BOUNDARY_ID::bigint,
    GEOMETRY.ID::bigint,
    GEOMETRY.CITY_ID::bigint
FROM BUSLANES.CITY_GEOMETRIES AS GEOMETRY
WHERE GEOMETRYTYPE(GEOMETRY.GEOM) IN ('LINESTRING', 'MULTILINESTRING')
  AND (
    ABS(GEOMETRY.LENGTH_M - ST_LENGTH(GEOMETRY.GEOM::GEOGRAPHY)) > 0.001
    OR ABS(
      GEOMETRY.LANE_LENGTH_M
      - ST_LENGTH(GEOMETRY.GEOM::GEOGRAPHY) * GEOMETRY.LANES
    ) > 0.001
  );

COMMENT ON VIEW BUSLANES.GEOMETRY_MODEL_INTEGRITY IS
    'Must remain empty. Diagnostic view for city/boundary/geometry ownership and derived-value invariants.';
