SET SEARCH_PATH = BUSLANES, PUBLIC;

-- V036 introduced CITY_ID as mandatory geometry ownership. The final model
-- keeps CITY_ID as a denormalized application link, while BOUNDARY_ID is the
-- authoritative spatial owner whenever it is present. Detached geometries must
-- survive OSM snapshot replacement and therefore CITY_ID may temporarily be
-- nullable as well.
ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ALTER COLUMN CITY_ID DROP NOT NULL;

ALTER TABLE BUSLANES.CITY_BOUNDARIES
    DROP CONSTRAINT IF EXISTS CITY_BOUNDARIES_CITY_ID_FKEY;
ALTER TABLE BUSLANES.CITY_BOUNDARIES
    ADD CONSTRAINT CITY_BOUNDARIES_CITY_ID_FKEY
        FOREIGN KEY (CITY_ID)
        REFERENCES BUSLANES.CITIES (ID)
        ON DELETE SET NULL;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    DROP CONSTRAINT IF EXISTS CITY_GEOMETRIES_CITY_ID_FKEY;
ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ADD CONSTRAINT CITY_GEOMETRIES_CITY_ID_FKEY
        FOREIGN KEY (CITY_ID)
        REFERENCES BUSLANES.CITIES (ID)
        ON DELETE SET NULL;

UPDATE BUSLANES.CITY_GEOMETRIES AS GEOMETRY
SET CITY_ID = BOUNDARY.CITY_ID,
    UPDATED_AT = NOW()
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
WHERE GEOMETRY.BOUNDARY_ID = BOUNDARY.ID
  AND GEOMETRY.CITY_ID IS DISTINCT FROM BOUNDARY.CITY_ID;

CREATE OR REPLACE FUNCTION BUSLANES.SYNC_GEOMETRY_CITY_FROM_BOUNDARY()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    BOUNDARY_CITY_ID BIGINT;
BEGIN
    IF NEW.BOUNDARY_ID IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT BOUNDARY.CITY_ID
    INTO BOUNDARY_CITY_ID
    FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
    WHERE BOUNDARY.ID = NEW.BOUNDARY_ID;

    IF FOUND THEN
        NEW.CITY_ID := BOUNDARY_CITY_ID;
    END IF;
    RETURN NEW;
END
$FUNCTION$;

DROP TRIGGER IF EXISTS CITY_GEOMETRIES_SYNC_CITY_FROM_BOUNDARY
    ON BUSLANES.CITY_GEOMETRIES;
CREATE TRIGGER CITY_GEOMETRIES_SYNC_CITY_FROM_BOUNDARY
BEFORE INSERT OR UPDATE OF BOUNDARY_ID, CITY_ID
ON BUSLANES.CITY_GEOMETRIES
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.SYNC_GEOMETRY_CITY_FROM_BOUNDARY();

CREATE OR REPLACE FUNCTION BUSLANES.PROPAGATE_BOUNDARY_CITY_TO_GEOMETRIES()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    IF OLD.CITY_ID IS DISTINCT FROM NEW.CITY_ID THEN
        UPDATE BUSLANES.CITY_GEOMETRIES
        SET CITY_ID = NEW.CITY_ID,
            UPDATED_AT = NOW()
        WHERE BOUNDARY_ID = NEW.ID
          AND CITY_ID IS DISTINCT FROM NEW.CITY_ID;
    END IF;
    RETURN NEW;
END
$FUNCTION$;

DROP TRIGGER IF EXISTS CITY_BOUNDARIES_PROPAGATE_CITY_TO_GEOMETRIES
    ON BUSLANES.CITY_BOUNDARIES;
CREATE TRIGGER CITY_BOUNDARIES_PROPAGATE_CITY_TO_GEOMETRIES
AFTER UPDATE OF CITY_ID
ON BUSLANES.CITY_BOUNDARIES
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.PROPAGATE_BOUNDARY_CITY_TO_GEOMETRIES();

-- The V036 active-boundary alignment trigger is superseded by the unconditional
-- propagation trigger above.
DROP TRIGGER IF EXISTS CITY_BOUNDARIES_ALIGN_GEOMETRIES
    ON BUSLANES.CITY_BOUNDARIES;

CREATE OR REPLACE VIEW BUSLANES.EFFECTIVE_CITY_GEOMETRIES AS
SELECT GEOMETRY.*
FROM BUSLANES.CITY_GEOMETRIES AS GEOMETRY
JOIN BUSLANES.CITY_BOUNDARIES AS BOUNDARY
  ON BOUNDARY.ID = GEOMETRY.BOUNDARY_ID
 AND BOUNDARY.IS_ACTIVE
 AND BOUNDARY.CITY_ID IS NOT NULL
 AND BOUNDARY.CITY_ID = GEOMETRY.CITY_ID;

COMMENT ON VIEW BUSLANES.EFFECTIVE_CITY_GEOMETRIES IS
    'Canonical geometry set for public output and metrics. Exact own OSM boundary must be active and agree with CITY_ID. IS_VISIBLE is intentionally ignored here.';

CREATE OR REPLACE VIEW BUSLANES.GEOMETRY_MODEL_INTEGRITY AS
SELECT
    'active-boundary-without-city'::text AS issue,
    BOUNDARY.ID::bigint AS boundary_id,
    NULL::bigint AS geometry_id,
    BOUNDARY.CITY_ID::bigint AS city_id
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
WHERE BOUNDARY.IS_ACTIVE
  AND BOUNDARY.CITY_ID IS NULL

UNION ALL

SELECT
    'active-boundary-city-identity-mismatch'::text,
    BOUNDARY.ID::bigint,
    NULL::bigint,
    BOUNDARY.CITY_ID::bigint
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
JOIN BUSLANES.CITIES AS CITY ON CITY.ID = BOUNDARY.CITY_ID
WHERE BOUNDARY.IS_ACTIVE
  AND (
    LOWER(REGEXP_REPLACE(CITY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
      <> LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_TYPE, '[[:space:]]+', '', 'g'))
    OR LOWER(REGEXP_REPLACE(CITY.NAME, '[[:space:]]+', '', 'g'))
      <> LOWER(REGEXP_REPLACE(BOUNDARY.DISPLAY_NAME, '[[:space:]]+', '', 'g'))
  )

UNION ALL

SELECT
    'geometry-boundary-city-mismatch'::text,
    BOUNDARY.ID::bigint,
    GEOMETRY.ID::bigint,
    GEOMETRY.CITY_ID::bigint
FROM BUSLANES.CITY_GEOMETRIES AS GEOMETRY
JOIN BUSLANES.CITY_BOUNDARIES AS BOUNDARY
  ON BOUNDARY.ID = GEOMETRY.BOUNDARY_ID
WHERE GEOMETRY.CITY_ID IS DISTINCT FROM BOUNDARY.CITY_ID

UNION ALL

SELECT
    'geometry-derived-line-value-mismatch'::text,
    GEOMETRY.BOUNDARY_ID::bigint,
    GEOMETRY.ID::bigint,
    GEOMETRY.CITY_ID::bigint
FROM BUSLANES.CITY_GEOMETRIES AS GEOMETRY
WHERE GEOMETRYTYPE(GEOMETRY.GEOM) IN ('LINESTRING', 'MULTILINESTRING')
  AND (
    ABS(GEOMETRY.LENGTH_M - ST_LENGTH(GEOMETRY.GEOM::GEOGRAPHY)) > 0.001
    OR ABS(
      GEOMETRY.LANE_LENGTH_M
      - ST_LENGTH(GEOMETRY.GEOM::GEOGRAPHY) * GEOMETRY.LANES
    ) > 0.001
  );

CREATE OR REPLACE FUNCTION BUSLANES.ASSERT_CITY_GEOMETRY_INVARIANTS()
RETURNS VOID
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    ISSUE_ROW RECORD;
BEGIN
    SELECT *
    INTO ISSUE_ROW
    FROM BUSLANES.GEOMETRY_MODEL_INTEGRITY
    LIMIT 1;

    IF FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = FORMAT(
                'Geometry model invariant violation: %s (boundary=%s geometry=%s city=%s)',
                ISSUE_ROW.ISSUE,
                ISSUE_ROW.BOUNDARY_ID,
                ISSUE_ROW.GEOMETRY_ID,
                ISSUE_ROW.CITY_ID
            );
    END IF;
END
$FUNCTION$;

SELECT BUSLANES.SYNC_ACTIVE_BOUNDARY_CITIES();

UPDATE BUSLANES.CITY_GEOMETRIES AS GEOMETRY
SET CITY_ID = BOUNDARY.CITY_ID,
    UPDATED_AT = NOW()
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
WHERE GEOMETRY.BOUNDARY_ID = BOUNDARY.ID
  AND GEOMETRY.CITY_ID IS DISTINCT FROM BOUNDARY.CITY_ID;

SELECT BUSLANES.ASSERT_CITY_GEOMETRY_INVARIANTS();
