SET SEARCH_PATH = BUSLANES, PUBLIC;

-- V036 used deferred row triggers whose NEW record reflected the intermediate
-- state that originally queued the trigger. That is incorrect for workflows
-- such as SYNC_ACTIVE_BOUNDARY_CITIES(), which may intentionally set CITY_ID
-- to NULL and then rebind it inside the same transaction. At COMMIT we must
-- validate the final relational state, not an obsolete row image.
DROP TRIGGER IF EXISTS CITY_BOUNDARIES_CONSISTENCY_CHECK
    ON BUSLANES.CITY_BOUNDARIES;
DROP TRIGGER IF EXISTS CITY_GEOMETRIES_CONSISTENCY_CHECK
    ON BUSLANES.CITY_GEOMETRIES;

CREATE OR REPLACE FUNCTION BUSLANES.VALIDATE_GEOMETRY_MODEL_FINAL_STATE()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    ISSUE_ROW RECORD;
BEGIN
    SELECT *
    INTO ISSUE_ROW
    FROM BUSLANES.GEOMETRY_MODEL_INTEGRITY
    LIMIT 1;

    IF FOUND THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = FORMAT(
                'Geometry model final-state violation: %s (boundary=%s geometry=%s city=%s)',
                ISSUE_ROW.ISSUE,
                ISSUE_ROW.BOUNDARY_ID,
                ISSUE_ROW.GEOMETRY_ID,
                ISSUE_ROW.CITY_ID
            );
    END IF;

    RETURN NULL;
END
$FUNCTION$;

CREATE CONSTRAINT TRIGGER CITY_BOUNDARIES_FINAL_STATE_CHECK
AFTER INSERT OR UPDATE OR DELETE
ON BUSLANES.CITY_BOUNDARIES
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.VALIDATE_GEOMETRY_MODEL_FINAL_STATE();

CREATE CONSTRAINT TRIGGER CITY_GEOMETRIES_FINAL_STATE_CHECK
AFTER INSERT OR UPDATE OR DELETE
ON BUSLANES.CITY_GEOMETRIES
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.VALIDATE_GEOMETRY_MODEL_FINAL_STATE();

COMMENT ON FUNCTION BUSLANES.VALIDATE_GEOMETRY_MODEL_FINAL_STATE() IS
    'Deferred integrity guard that validates current transaction-final city/boundary/geometry state instead of stale trigger NEW/OLD images.';

SELECT BUSLANES.ASSERT_CITY_GEOMETRY_INVARIANTS();
