SET SEARCH_PATH = BUSLANES, PUBLIC;

-- Geometry ownership follows an active OSM boundary only while that boundary
-- is active. When the boundary is disabled or removed, preserve the geometry
-- as a suspended city-owned row (BOUNDARY_ID = NULL). When another boundary
-- for the same logical city becomes active, attach all suspended geometries to
-- that boundary automatically.

CREATE OR REPLACE FUNCTION BUSLANES.RECONCILE_GEOMETRY_BOUNDARY_OWNERSHIP()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    IF TG_OP = 'UPDATE'
       AND OLD.IS_ACTIVE
       AND NOT NEW.IS_ACTIVE THEN
        UPDATE BUSLANES.CITY_GEOMETRIES
        SET BOUNDARY_ID = NULL,
            UPDATED_AT = NOW()
        WHERE BOUNDARY_ID = NEW.ID;
    END IF;

    IF NEW.IS_ACTIVE
       AND NEW.CITY_ID IS NOT NULL THEN
        UPDATE BUSLANES.CITY_GEOMETRIES
        SET BOUNDARY_ID = NEW.ID,
            UPDATED_AT = NOW()
        WHERE CITY_ID = NEW.CITY_ID
          AND BOUNDARY_ID IS NULL;
    END IF;

    RETURN NEW;
END
$FUNCTION$;

DROP TRIGGER IF EXISTS CITY_BOUNDARIES_RECONCILE_GEOMETRIES_UPDATE
    ON BUSLANES.CITY_BOUNDARIES;
CREATE TRIGGER CITY_BOUNDARIES_RECONCILE_GEOMETRIES_UPDATE
AFTER UPDATE OF IS_ACTIVE, CITY_ID
ON BUSLANES.CITY_BOUNDARIES
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.RECONCILE_GEOMETRY_BOUNDARY_OWNERSHIP();

DROP TRIGGER IF EXISTS CITY_BOUNDARIES_RECONCILE_GEOMETRIES_INSERT
    ON BUSLANES.CITY_BOUNDARIES;
CREATE TRIGGER CITY_BOUNDARIES_RECONCILE_GEOMETRIES_INSERT
AFTER INSERT
ON BUSLANES.CITY_BOUNDARIES
FOR EACH ROW
EXECUTE FUNCTION BUSLANES.RECONCILE_GEOMETRY_BOUNDARY_OWNERSHIP();

-- Repair existing rows left attached to inactive boundaries by earlier
-- versions of the application.
UPDATE BUSLANES.CITY_GEOMETRIES AS GEOMETRY
SET BOUNDARY_ID = NULL,
    UPDATED_AT = NOW()
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
WHERE GEOMETRY.BOUNDARY_ID = BOUNDARY.ID
  AND NOT BOUNDARY.IS_ACTIVE;

-- If an active replacement already exists, attach suspended rows immediately.
UPDATE BUSLANES.CITY_GEOMETRIES AS GEOMETRY
SET BOUNDARY_ID = BOUNDARY.ID,
    UPDATED_AT = NOW()
FROM BUSLANES.CITY_BOUNDARIES AS BOUNDARY
WHERE GEOMETRY.BOUNDARY_ID IS NULL
  AND GEOMETRY.CITY_ID = BOUNDARY.CITY_ID
  AND BOUNDARY.IS_ACTIVE
  AND BOUNDARY.CITY_ID IS NOT NULL;

COMMENT ON FUNCTION BUSLANES.RECONCILE_GEOMETRY_BOUNDARY_OWNERSHIP() IS
    'Suspends geometries when their OSM boundary becomes inactive and reattaches suspended geometries when a boundary for the same city becomes active.';

SELECT BUSLANES.ASSERT_CITY_GEOMETRY_INVARIANTS();
