SET SEARCH_PATH = BUSLANES, PUBLIC;

CREATE TABLE IF NOT EXISTS BUSLANES.GEOMETRY_EDIT_LEASES
(
    GEOMETRY_ID BIGINT PRIMARY KEY
        REFERENCES BUSLANES.CITY_GEOMETRIES (ID)
        ON DELETE CASCADE,
    TOKEN TEXT NOT NULL UNIQUE,
    USER_ID BIGINT NOT NULL
        REFERENCES BUSLANES.ADMIN_USERS (ID)
        ON DELETE CASCADE,
    CLIENT_ID TEXT NOT NULL,
    GENERATION BIGINT NOT NULL DEFAULT 1
        CHECK (GENERATION > 0),
    ACQUIRED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    LAST_SEEN_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    CONSTRAINT GEOMETRY_EDIT_LEASES_TOKEN_LENGTH CHECK (
        CHAR_LENGTH(TOKEN) BETWEEN 16 AND 256
    ),
    CONSTRAINT GEOMETRY_EDIT_LEASES_CLIENT_LENGTH CHECK (
        CHAR_LENGTH(CLIENT_ID) BETWEEN 1 AND 128
    ),
    CONSTRAINT GEOMETRY_EDIT_LEASES_EXPIRY_CHECK CHECK (
        EXPIRES_AT > LAST_SEEN_AT
    )
);

CREATE INDEX IF NOT EXISTS GEOMETRY_EDIT_LEASES_EXPIRES_IDX
    ON BUSLANES.GEOMETRY_EDIT_LEASES (EXPIRES_AT);

COMMENT ON TABLE BUSLANES.GEOMETRY_EDIT_LEASES IS
    'Short-lived cooperative edit leases for existing geometries. The opaque token is persisted by the owning browser workspace and revalidated after reload.';
COMMENT ON COLUMN BUSLANES.GEOMETRY_EDIT_LEASES.GENERATION IS
    'Monotonic per-geometry lease generation. Force takeover and expired reacquisition advance it so stale browser state cannot silently resume.';
