SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.ADMIN_SECURITY_SETTINGS
    ADD COLUMN IF NOT EXISTS REQUEST_RATE_LIMIT_USER_PER_MINUTE INTEGER NOT NULL DEFAULT 600,
    ADD COLUMN IF NOT EXISTS REQUEST_RATE_LIMIT_GLOBAL_PER_MINUTE INTEGER NOT NULL DEFAULT 5000;

ALTER TABLE BUSLANES.ADMIN_SECURITY_SETTINGS
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_REQUEST_RATE_USER_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_REQUEST_RATE_USER_CHECK CHECK (
        REQUEST_RATE_LIMIT_USER_PER_MINUTE BETWEEN 10 AND 60000
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_REQUEST_RATE_GLOBAL_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_REQUEST_RATE_GLOBAL_CHECK CHECK (
        REQUEST_RATE_LIMIT_GLOBAL_PER_MINUTE BETWEEN 10 AND 1000000
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_REQUEST_RATE_ORDER_CHECK,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_REQUEST_RATE_ORDER_CHECK CHECK (
        REQUEST_RATE_LIMIT_GLOBAL_PER_MINUTE >= REQUEST_RATE_LIMIT_USER_PER_MINUTE
    );

COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.REQUEST_RATE_LIMIT_USER_PER_MINUTE IS
    'Maximum authenticated administrative HTTP requests accepted from one user in one fixed one-minute application window.';
COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.REQUEST_RATE_LIMIT_GLOBAL_PER_MINUTE IS
    'Maximum authenticated administrative HTTP requests accepted across all users in one fixed one-minute application window.';
