SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.ADMIN_LOGIN_IP_STATE
    ADD COLUMN IF NOT EXISTS REQUEST_INCIDENT_COUNT INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS REQUEST_INCIDENT_WINDOW_STARTED_AT TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS REQUEST_LOCKED_UNTIL TIMESTAMPTZ;

ALTER TABLE BUSLANES.ADMIN_LOGIN_IP_STATE
    DROP CONSTRAINT IF EXISTS ADMIN_LOGIN_IP_STATE_REQUEST_INCIDENT_COUNT_CHECK,
    ADD CONSTRAINT ADMIN_LOGIN_IP_STATE_REQUEST_INCIDENT_COUNT_CHECK CHECK (
        REQUEST_INCIDENT_COUNT >= 0
    );

CREATE INDEX IF NOT EXISTS ADMIN_LOGIN_IP_STATE_REQUEST_LOCKED_UNTIL_IDX
    ON BUSLANES.ADMIN_LOGIN_IP_STATE (REQUEST_LOCKED_UNTIL)
    WHERE REQUEST_LOCKED_UNTIL IS NOT NULL;

COMMENT ON COLUMN BUSLANES.ADMIN_LOGIN_IP_STATE.REQUEST_INCIDENT_COUNT IS
    'Strict API-contract/security-probing violations in the current request-security window.';
COMMENT ON COLUMN BUSLANES.ADMIN_LOGIN_IP_STATE.REQUEST_INCIDENT_WINDOW_STARTED_AT IS
    'Start of the current strict API-contract/security-probing window.';
COMMENT ON COLUMN BUSLANES.ADMIN_LOGIN_IP_STATE.REQUEST_LOCKED_UNTIL IS
    'Automatic request-security IP lockout, independent from failed-login lockout.';
