SET SEARCH_PATH = BUSLANES, PUBLIC;

CREATE TABLE BUSLANES.POINT_TYPES (
    ID BIGSERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    DISPLAY_WIDTH SMALLINT NOT NULL DEFAULT 32,
    DISPLAY_HEIGHT SMALLINT NOT NULL DEFAULT 32,
    ANCHOR_X DOUBLE PRECISION NOT NULL DEFAULT 16,
    ANCHOR_Y DOUBLE PRECISION NOT NULL DEFAULT 16,
    ICON_FILE_NAME TEXT,
    ICON_MIME TEXT,
    ICON_SOURCE_WIDTH INTEGER,
    ICON_SOURCE_HEIGHT INTEGER,
    ICON_SHA256 TEXT,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT POINT_TYPES_NAME_LENGTH CHECK (
        CHAR_LENGTH(BTRIM(NAME)) BETWEEN 1 AND 120
    ),
    CONSTRAINT POINT_TYPES_DISPLAY_SIZE CHECK (
        DISPLAY_WIDTH BETWEEN 8 AND 256
        AND DISPLAY_HEIGHT BETWEEN 8 AND 256
    ),
    CONSTRAINT POINT_TYPES_ANCHOR_BOUNDS CHECK (
        ANCHOR_X >= 0
        AND ANCHOR_X <= DISPLAY_WIDTH
        AND ANCHOR_Y >= 0
        AND ANCHOR_Y <= DISPLAY_HEIGHT
    ),
    CONSTRAINT POINT_TYPES_ICON_METADATA CHECK (
        (
            ICON_FILE_NAME IS NULL
            AND ICON_MIME IS NULL
            AND ICON_SOURCE_WIDTH IS NULL
            AND ICON_SOURCE_HEIGHT IS NULL
            AND ICON_SHA256 IS NULL
        )
        OR
        (
            ICON_FILE_NAME IS NOT NULL
            AND ICON_MIME IN (
                'image/png',
                'image/gif',
                'image/svg+xml'
            )
            AND ICON_SOURCE_WIDTH BETWEEN 1 AND 4096
            AND ICON_SOURCE_HEIGHT BETWEEN 1 AND 4096
            AND ICON_SHA256 ~ '^[0-9a-f]{64}$'
            AND ICON_FILE_NAME ~ '^[0-9]+-[0-9a-f]{64}\.(png|gif|svg)$'
        )
    )
);

CREATE UNIQUE INDEX POINT_TYPES_NAME_LOWER_UIDX
    ON BUSLANES.POINT_TYPES (LOWER(BTRIM(NAME)));

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ADD COLUMN POINT_TYPE_ID BIGINT
        REFERENCES BUSLANES.POINT_TYPES(ID)
        ON DELETE SET NULL;

CREATE INDEX CITY_GEOMETRIES_POINT_TYPE_IDX
    ON BUSLANES.CITY_GEOMETRIES (POINT_TYPE_ID, ID)
    WHERE POINT_TYPE_ID IS NOT NULL;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    DROP CONSTRAINT IF EXISTS CITY_GEOMETRIES_LINE_STATE;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ADD CONSTRAINT CITY_GEOMETRIES_LINE_STATE CHECK (
        (
            GEOMETRYTYPE(GEOM) IN ('LINESTRING', 'MULTILINESTRING')
            AND LINE_TYPE_ID IS NOT NULL
            AND LANES IN (1, 2)
            AND LENGTH_M IS NOT NULL
            AND LANE_LENGTH_M IS NOT NULL
            AND POINT_TYPE_ID IS NULL
        )
        OR
        (
            GEOMETRYTYPE(GEOM) = 'POINT'
            AND LINE_TYPE_ID IS NULL
            AND LANES IS NULL
            AND LENGTH_M IS NULL
            AND LANE_LENGTH_M IS NULL
        )
        OR
        (
            GEOMETRYTYPE(GEOM) IN ('POLYGON', 'MULTIPOLYGON')
            AND LINE_TYPE_ID IS NULL
            AND LANES IS NULL
            AND LENGTH_M IS NULL
            AND LANE_LENGTH_M IS NULL
            AND POINT_TYPE_ID IS NULL
        )
    );

CREATE OR REPLACE FUNCTION BUSLANES.NORMALIZE_CITY_GEOMETRY_DERIVED()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    IF GEOMETRYTYPE(NEW.GEOM) IN ('LINESTRING', 'MULTILINESTRING') THEN
        NEW.LENGTH_M := ST_LENGTH(NEW.GEOM::GEOGRAPHY);
        NEW.LANE_LENGTH_M := NEW.LENGTH_M * NEW.LANES;
    ELSE
        NEW.LENGTH_M := NULL;
        NEW.LANE_LENGTH_M := NULL;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF NEW.GEOM IS DISTINCT FROM OLD.GEOM
           OR NEW.LINE_TYPE_ID IS DISTINCT FROM OLD.LINE_TYPE_ID
           OR NEW.POINT_TYPE_ID IS DISTINCT FROM OLD.POINT_TYPE_ID
           OR NEW.LANES IS DISTINCT FROM OLD.LANES
           OR NEW.PROPERTIES IS DISTINCT FROM OLD.PROPERTIES
           OR NEW.DISPLAY_NAME IS DISTINCT FROM OLD.DISPLAY_NAME
           OR NEW.TOOLTIP IS DISTINCT FROM OLD.TOOLTIP
           OR NEW.TAGS IS DISTINCT FROM OLD.TAGS
           OR NEW.SOURCE_TAGS IS DISTINCT FROM OLD.SOURCE_TAGS
           OR NEW.IS_VISIBLE IS DISTINCT FROM OLD.IS_VISIBLE
           OR NEW.WAS_EDITED IS DISTINCT FROM OLD.WAS_EDITED THEN
            NEW.UPDATED_AT := NOW();
        ELSE
            NEW.UPDATED_AT := OLD.UPDATED_AT;
        END IF;
    END IF;

    RETURN NEW;
END
$FUNCTION$;

COMMENT ON TABLE BUSLANES.POINT_TYPES IS
    'Administrator-managed point categories and render metadata. Icon files are stored outside PostgreSQL and referenced by safe generated file names.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.POINT_TYPE_ID IS
    'Optional point-category reference. Must be NULL for line and polygon geometries.';
