SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.ADMIN_SECURITY_SETTINGS
    ADD COLUMN IF NOT EXISTS METRICS_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS METRICS_BEARER_TOKEN_HASH BYTEA,
    ADD COLUMN IF NOT EXISTS METRICS_SETTINGS_INITIALIZED BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE BUSLANES.ADMIN_SECURITY_SETTINGS
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_METRICS_TOKEN_HASH_LENGTH,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_METRICS_TOKEN_HASH_LENGTH CHECK (
        METRICS_BEARER_TOKEN_HASH IS NULL
        OR OCTET_LENGTH(METRICS_BEARER_TOKEN_HASH) = 32
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_SECURITY_SETTINGS_METRICS_ENABLED_TOKEN,
    ADD CONSTRAINT ADMIN_SECURITY_SETTINGS_METRICS_ENABLED_TOKEN CHECK (
        NOT METRICS_ENABLED
        OR METRICS_BEARER_TOKEN_HASH IS NOT NULL
    );

COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.METRICS_ENABLED IS
    'Whether the Prometheus-compatible /metrics endpoint is enabled.';
COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.METRICS_BEARER_TOKEN_HASH IS
    'SHA-256 hash of the Prometheus bearer token. Plaintext is never persisted.';
COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.METRICS_SETTINGS_INITIALIZED IS
    'One-time bootstrap marker preventing environment values from overriding admin-managed metrics settings.';
