SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.ADMIN_USERS
    ADD COLUMN IF NOT EXISTS MFA_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS MFA_SECRET_CIPHERTEXT BYTEA,
    ADD COLUMN IF NOT EXISTS MFA_PENDING_SECRET_CIPHERTEXT BYTEA,
    ADD COLUMN IF NOT EXISTS MFA_PENDING_CREATED_AT TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS MFA_LAST_USED_STEP BIGINT,
    ADD COLUMN IF NOT EXISTS MFA_ENROLLED_AT TIMESTAMPTZ;

ALTER TABLE BUSLANES.ADMIN_USERS
    DROP CONSTRAINT IF EXISTS ADMIN_USERS_MFA_ENABLED_SECRET,
    ADD CONSTRAINT ADMIN_USERS_MFA_ENABLED_SECRET CHECK (
        (
            MFA_ENABLED
            AND MFA_SECRET_CIPHERTEXT IS NOT NULL
            AND MFA_ENROLLED_AT IS NOT NULL
        )
        OR
        (
            NOT MFA_ENABLED
            AND MFA_SECRET_CIPHERTEXT IS NULL
            AND MFA_ENROLLED_AT IS NULL
        )
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_USERS_MFA_PENDING_PAIR,
    ADD CONSTRAINT ADMIN_USERS_MFA_PENDING_PAIR CHECK (
        (
            MFA_PENDING_SECRET_CIPHERTEXT IS NULL
            AND MFA_PENDING_CREATED_AT IS NULL
        )
        OR
        (
            MFA_PENDING_SECRET_CIPHERTEXT IS NOT NULL
            AND MFA_PENDING_CREATED_AT IS NOT NULL
        )
    ),
    DROP CONSTRAINT IF EXISTS ADMIN_USERS_MFA_LAST_USED_STEP,
    ADD CONSTRAINT ADMIN_USERS_MFA_LAST_USED_STEP CHECK (
        MFA_LAST_USED_STEP IS NULL
        OR MFA_LAST_USED_STEP >= 0
    );

CREATE TABLE IF NOT EXISTS BUSLANES.ADMIN_MFA_RECOVERY_CODES (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL
        REFERENCES BUSLANES.ADMIN_USERS(ID)
        ON DELETE CASCADE,
    CODE_HASH BYTEA NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    USED_AT TIMESTAMPTZ,
    CONSTRAINT ADMIN_MFA_RECOVERY_CODES_HASH_LENGTH CHECK (
        OCTET_LENGTH(CODE_HASH) = 32
    ),
    CONSTRAINT ADMIN_MFA_RECOVERY_CODES_USER_HASH_UIDX UNIQUE (
        USER_ID,
        CODE_HASH
    )
);

CREATE INDEX IF NOT EXISTS ADMIN_MFA_RECOVERY_CODES_UNUSED_IDX
    ON BUSLANES.ADMIN_MFA_RECOVERY_CODES (USER_ID, ID)
    WHERE USED_AT IS NULL;

CREATE TABLE IF NOT EXISTS BUSLANES.ADMIN_MFA_CHALLENGES (
    TOKEN_HASH BYTEA PRIMARY KEY,
    USER_ID BIGINT NOT NULL
        REFERENCES BUSLANES.ADMIN_USERS(ID)
        ON DELETE CASCADE,
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    IP_ADDRESS INET,
    USER_AGENT TEXT,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ADMIN_MFA_CHALLENGES_HASH_LENGTH CHECK (
        OCTET_LENGTH(TOKEN_HASH) = 32
    ),
    CONSTRAINT ADMIN_MFA_CHALLENGES_EXPIRY CHECK (
        EXPIRES_AT > CREATED_AT
    )
);

CREATE INDEX IF NOT EXISTS ADMIN_MFA_CHALLENGES_EXPIRY_IDX
    ON BUSLANES.ADMIN_MFA_CHALLENGES (EXPIRES_AT);

COMMENT ON COLUMN BUSLANES.ADMIN_USERS.MFA_SECRET_CIPHERTEXT IS
    'AES-256-GCM encrypted TOTP secret. The encryption key is deployment configuration and is never stored in PostgreSQL.';
COMMENT ON COLUMN BUSLANES.ADMIN_USERS.MFA_PENDING_SECRET_CIPHERTEXT IS
    'Encrypted TOTP secret awaiting enrollment confirmation.';
COMMENT ON TABLE BUSLANES.ADMIN_MFA_RECOVERY_CODES IS
    'One-way SHA-256 hashes of administrator MFA recovery codes.';
COMMENT ON TABLE BUSLANES.ADMIN_MFA_CHALLENGES IS
    'Short-lived one-time pre-session challenges issued after successful password verification.';
