SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.ADMIN_SECURITY_SETTINGS
    ADD COLUMN IF NOT EXISTS MFA_REQUIRED BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN BUSLANES.ADMIN_SECURITY_SETTINGS.MFA_REQUIRED IS
    'Require administrators without enrolled MFA to remain in profile-only enrollment mode.';
