SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    ADD COLUMN IF NOT EXISTS MIN_ZOOM DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS MAX_ZOOM DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS VALID_FROM DATE,
    ADD COLUMN IF NOT EXISTS VALID_TO DATE;

ALTER TABLE BUSLANES.CITY_GEOMETRIES
    DROP CONSTRAINT IF EXISTS CITY_GEOMETRIES_ZOOM_RANGE,
    ADD CONSTRAINT CITY_GEOMETRIES_ZOOM_RANGE CHECK (
        (MIN_ZOOM IS NULL OR MIN_ZOOM BETWEEN 0 AND 24)
        AND (MAX_ZOOM IS NULL OR MAX_ZOOM BETWEEN 0 AND 24)
        AND (
            MIN_ZOOM IS NULL
            OR MAX_ZOOM IS NULL
            OR MIN_ZOOM <= MAX_ZOOM
        )
    ),
    DROP CONSTRAINT IF EXISTS CITY_GEOMETRIES_VALID_DATES,
    ADD CONSTRAINT CITY_GEOMETRIES_VALID_DATES CHECK (
        VALID_FROM IS NULL
        OR VALID_TO IS NULL
        OR VALID_FROM <= VALID_TO
    );

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    ADD COLUMN IF NOT EXISTS SHOW_GEOMETRY_TIMELINE BOOLEAN NOT NULL DEFAULT FALSE;

CREATE OR REPLACE FUNCTION BUSLANES.NORMALIZE_CITY_GEOMETRY_DERIVED()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    IF GEOMETRYTYPE(NEW.GEOM) IN ('LINESTRING', 'MULTILINESTRING') THEN
        NEW.LENGTH_M := ST_LENGTH(NEW.GEOM::GEOGRAPHY);
        NEW.LANE_LENGTH_M := NEW.LENGTH_M * NEW.LANES;
    ELSE
        NEW.LENGTH_M := NULL;
        NEW.LANE_LENGTH_M := NULL;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF NEW.GEOM IS DISTINCT FROM OLD.GEOM
           OR NEW.LINE_TYPE_ID IS DISTINCT FROM OLD.LINE_TYPE_ID
           OR NEW.POINT_TYPE_ID IS DISTINCT FROM OLD.POINT_TYPE_ID
           OR NEW.LANES IS DISTINCT FROM OLD.LANES
           OR NEW.PROPERTIES IS DISTINCT FROM OLD.PROPERTIES
           OR NEW.DISPLAY_NAME IS DISTINCT FROM OLD.DISPLAY_NAME
           OR NEW.TOOLTIP IS DISTINCT FROM OLD.TOOLTIP
           OR NEW.TAGS IS DISTINCT FROM OLD.TAGS
           OR NEW.SOURCE_TAGS IS DISTINCT FROM OLD.SOURCE_TAGS
           OR NEW.IS_VISIBLE IS DISTINCT FROM OLD.IS_VISIBLE
           OR NEW.MIN_ZOOM IS DISTINCT FROM OLD.MIN_ZOOM
           OR NEW.MAX_ZOOM IS DISTINCT FROM OLD.MAX_ZOOM
           OR NEW.VALID_FROM IS DISTINCT FROM OLD.VALID_FROM
           OR NEW.VALID_TO IS DISTINCT FROM OLD.VALID_TO
           OR NEW.WAS_EDITED IS DISTINCT FROM OLD.WAS_EDITED THEN
            NEW.UPDATED_AT := NOW();
        ELSE
            NEW.UPDATED_AT := OLD.UPDATED_AT;
        END IF;
    END IF;

    RETURN NEW;
END
$FUNCTION$;

COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.MIN_ZOOM IS
    'Optional minimum map zoom at which the geometry is visible.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.MAX_ZOOM IS
    'Optional maximum map zoom at which the geometry is visible.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.VALID_FROM IS
    'Optional first calendar date on which the geometry is active.';
COMMENT ON COLUMN BUSLANES.CITY_GEOMETRIES.VALID_TO IS
    'Optional last calendar date on which the geometry is active.';
COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.SHOW_GEOMETRY_TIMELINE IS
    'Whether the public map exposes geometry validity timeline controls.';
