SET SEARCH_PATH = BUSLANES, PUBLIC;

CREATE TABLE IF NOT EXISTS BUSLANES.GEOMETRY_DISCUSSION_MESSAGES
(
    ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GEOMETRY_ID       BIGINT      NOT NULL
                                  REFERENCES BUSLANES.CITY_GEOMETRIES (ID)
                                  ON DELETE CASCADE,
    AUTHOR_USER_ID    BIGINT
                                  REFERENCES BUSLANES.ADMIN_USERS (ID)
                                  ON DELETE SET NULL,
    GEOMETRY_REVISION TIMESTAMPTZ,
    MESSAGE           TEXT        NOT NULL,
    CREATED_AT        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    EDITED_AT         TIMESTAMPTZ,
    DELETED_AT        TIMESTAMPTZ,
    CONSTRAINT GEOMETRY_DISCUSSION_MESSAGE_LENGTH CHECK (
        CHAR_LENGTH(BTRIM(MESSAGE)) BETWEEN 1 AND 4000
    )
);

CREATE INDEX IF NOT EXISTS GEOMETRY_DISCUSSION_MESSAGES_GEOMETRY_ID_IDX
    ON BUSLANES.GEOMETRY_DISCUSSION_MESSAGES (GEOMETRY_ID, ID);

CREATE INDEX IF NOT EXISTS GEOMETRY_DISCUSSION_MESSAGES_AUTHOR_USER_ID_IDX
    ON BUSLANES.GEOMETRY_DISCUSSION_MESSAGES (AUTHOR_USER_ID, ID);

COMMENT ON TABLE BUSLANES.GEOMETRY_DISCUSSION_MESSAGES IS
    'Persistent human discussion attached to an editable geometry; separate from immutable administrator audit events.';
COMMENT ON COLUMN BUSLANES.GEOMETRY_DISCUSSION_MESSAGES.GEOMETRY_REVISION IS
    'Geometry UPDATED_AT value observed when the message was created, allowing the discussion to be correlated with the geometry revision.';
COMMENT ON COLUMN BUSLANES.GEOMETRY_DISCUSSION_MESSAGES.DELETED_AT IS
    'Reserved for soft deletion; non-null messages are excluded from the normal discussion feed.';
