SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    ADD COLUMN IF NOT EXISTS SHOW_POINT_GEOMETRIES BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS SHOW_LINE_GEOMETRIES BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS SHOW_POLYGON_GEOMETRIES BOOLEAN NOT NULL DEFAULT TRUE;

COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.SHOW_POINT_GEOMETRIES IS
    'Whether Point/POI geometries are available on the public map.';
COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.SHOW_LINE_GEOMETRIES IS
    'Whether line geometries are available on the public map.';
COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.SHOW_POLYGON_GEOMETRIES IS
    'Whether polygon geometries are available on the public map.';
