SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.POINT_TYPES
    ADD COLUMN IF NOT EXISTS MIN_ZOOM DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS MAX_ZOOM DOUBLE PRECISION;

ALTER TABLE BUSLANES.POINT_TYPES
    DROP CONSTRAINT IF EXISTS POINT_TYPES_ZOOM_RANGE,
    ADD CONSTRAINT POINT_TYPES_ZOOM_RANGE CHECK (
        (MIN_ZOOM IS NULL OR MIN_ZOOM BETWEEN 0 AND 24)
        AND (MAX_ZOOM IS NULL OR MAX_ZOOM BETWEEN 0 AND 24)
        AND (
            MIN_ZOOM IS NULL
            OR MAX_ZOOM IS NULL
            OR MIN_ZOOM <= MAX_ZOOM
        )
    );

COMMENT ON COLUMN BUSLANES.POINT_TYPES.MIN_ZOOM IS
    'Optional minimum public-map zoom for every Point geometry assigned to this point type.';
COMMENT ON COLUMN BUSLANES.POINT_TYPES.MAX_ZOOM IS
    'Optional maximum public-map zoom for every Point geometry assigned to this point type.';
