SET SEARCH_PATH = BUSLANES, PUBLIC;

ALTER TABLE BUSLANES.PROJECT_SETTINGS
    ADD COLUMN IF NOT EXISTS HISTORY_START_DATE DATE;

CREATE TABLE BUSLANES.GEOMETRY_HISTORY_SPEEDS (
    ID BIGSERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    STEP_UNIT TEXT NOT NULL,
    INTERVAL_SECONDS DOUBLE PRECISION NOT NULL,
    SORT_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    IS_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT GEOMETRY_HISTORY_SPEEDS_NAME_LENGTH CHECK (
        CHAR_LENGTH(BTRIM(NAME)) BETWEEN 1 AND 40
    ),
    CONSTRAINT GEOMETRY_HISTORY_SPEEDS_STEP_UNIT CHECK (
        STEP_UNIT IN (
            'day',
            'week',
            'month',
            'quarter',
            'year',
            'five_years',
            'decade'
        )
    ),
    CONSTRAINT GEOMETRY_HISTORY_SPEEDS_INTERVAL CHECK (
        INTERVAL_SECONDS BETWEEN 0.1 AND 60
    ),
    CONSTRAINT GEOMETRY_HISTORY_SPEEDS_SORT_ORDER CHECK (
        SORT_ORDER BETWEEN 0 AND 1000000
    )
);

CREATE UNIQUE INDEX GEOMETRY_HISTORY_SPEEDS_ONE_DEFAULT_UIDX
    ON BUSLANES.GEOMETRY_HISTORY_SPEEDS ((IS_DEFAULT))
    WHERE IS_DEFAULT;

INSERT INTO BUSLANES.GEOMETRY_HISTORY_SPEEDS (
    NAME,
    STEP_UNIT,
    INTERVAL_SECONDS,
    SORT_ORDER,
    IS_ACTIVE,
    IS_DEFAULT
)
SELECT *
FROM (
    VALUES
        ('1x', 'month', 1.0::double precision, 10, TRUE, TRUE),
        ('2x', 'month', 0.5::double precision, 20, TRUE, FALSE),
        ('5x', 'quarter', 0.5::double precision, 30, TRUE, FALSE),
        ('10x', 'year', 0.5::double precision, 40, TRUE, FALSE)
) AS defaults(
    NAME,
    STEP_UNIT,
    INTERVAL_SECONDS,
    SORT_ORDER,
    IS_ACTIVE,
    IS_DEFAULT
)
WHERE NOT EXISTS (
    SELECT 1
    FROM BUSLANES.GEOMETRY_HISTORY_SPEEDS
);

COMMENT ON COLUMN BUSLANES.PROJECT_SETTINGS.HISTORY_START_DATE IS
    'Optional configured start of the public geometry history scale. NULL derives the start from published geometry validity dates.';
COMMENT ON TABLE BUSLANES.GEOMETRY_HISTORY_SPEEDS IS
    'Administrator-configured public history playback speed profiles.';
