SET SEARCH_PATH = BUSLANES, PUBLIC;

-- Generalize the existing geometry discussion storage in-place so message IDs,
-- read positions and existing history remain stable.
ALTER TABLE BUSLANES.GEOMETRY_DISCUSSION_READ_STATE
    DROP CONSTRAINT IF EXISTS GEOMETRY_DISCUSSION_READ_STATE_GEOMETRY_ID_FKEY;

ALTER TABLE BUSLANES.GEOMETRY_DISCUSSION_READ_STATE
    DROP CONSTRAINT IF EXISTS GEOMETRY_DISCUSSION_READ_STATE_LAST_READ_MESSAGE_ID_FKEY;

ALTER TABLE BUSLANES.GEOMETRY_DISCUSSION_MESSAGES
    DROP CONSTRAINT IF EXISTS GEOMETRY_DISCUSSION_MESSAGES_GEOMETRY_ID_FKEY;

ALTER TABLE BUSLANES.GEOMETRY_DISCUSSION_MESSAGES
    RENAME TO ADMIN_DISCUSSION_MESSAGES;

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_MESSAGES
    RENAME COLUMN GEOMETRY_ID TO SUBJECT_ID;

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_MESSAGES
    RENAME COLUMN GEOMETRY_REVISION TO SUBJECT_REVISION;

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_MESSAGES
    ADD COLUMN SUBJECT_TYPE TEXT NOT NULL DEFAULT 'geometry';

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_MESSAGES
    ALTER COLUMN SUBJECT_TYPE DROP DEFAULT;

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_MESSAGES
    ADD CONSTRAINT ADMIN_DISCUSSION_MESSAGES_SUBJECT_TYPE_CHECK
    CHECK (SUBJECT_TYPE IN ('geometry', 'osm-boundary'));

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_MESSAGES
    ADD CONSTRAINT ADMIN_DISCUSSION_MESSAGES_ID_SUBJECT_UNIQUE
    UNIQUE (ID, SUBJECT_TYPE, SUBJECT_ID);

DROP INDEX IF EXISTS BUSLANES.GEOMETRY_DISCUSSION_MESSAGES_GEOMETRY_ID_IDX;

CREATE INDEX IF NOT EXISTS ADMIN_DISCUSSION_MESSAGES_SUBJECT_IDX
    ON BUSLANES.ADMIN_DISCUSSION_MESSAGES (SUBJECT_TYPE, SUBJECT_ID, ID);

ALTER TABLE BUSLANES.GEOMETRY_DISCUSSION_READ_STATE
    RENAME TO ADMIN_DISCUSSION_READ_STATE;

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_READ_STATE
    RENAME COLUMN GEOMETRY_ID TO SUBJECT_ID;

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_READ_STATE
    ADD COLUMN SUBJECT_TYPE TEXT NOT NULL DEFAULT 'geometry';

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_READ_STATE
    ALTER COLUMN SUBJECT_TYPE DROP DEFAULT;

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_READ_STATE
    DROP CONSTRAINT IF EXISTS GEOMETRY_DISCUSSION_READ_STATE_PKEY;

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_READ_STATE
    ADD CONSTRAINT ADMIN_DISCUSSION_READ_STATE_PKEY
    PRIMARY KEY (SUBJECT_TYPE, SUBJECT_ID, USER_ID);

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_READ_STATE
    ADD CONSTRAINT ADMIN_DISCUSSION_READ_STATE_SUBJECT_TYPE_CHECK
    CHECK (SUBJECT_TYPE IN ('geometry', 'osm-boundary'));

CREATE OR REPLACE FUNCTION BUSLANES.CLEAR_ADMIN_DISCUSSION_READ_STATE_MESSAGE()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $
BEGIN
    UPDATE BUSLANES.ADMIN_DISCUSSION_READ_STATE
       SET LAST_READ_MESSAGE_ID = NULL
     WHERE LAST_READ_MESSAGE_ID = OLD.ID
       AND SUBJECT_TYPE = OLD.SUBJECT_TYPE
       AND SUBJECT_ID = OLD.SUBJECT_ID;

    RETURN OLD;
END;
$;

DROP TRIGGER IF EXISTS ADMIN_DISCUSSION_MESSAGES_CLEAR_READ_STATE
    ON BUSLANES.ADMIN_DISCUSSION_MESSAGES;

CREATE TRIGGER ADMIN_DISCUSSION_MESSAGES_CLEAR_READ_STATE
    BEFORE DELETE ON BUSLANES.ADMIN_DISCUSSION_MESSAGES
    FOR EACH ROW
    EXECUTE FUNCTION BUSLANES.CLEAR_ADMIN_DISCUSSION_READ_STATE_MESSAGE();

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_READ_STATE
    ADD CONSTRAINT ADMIN_DISCUSSION_READ_STATE_MESSAGE_FKEY
    FOREIGN KEY (LAST_READ_MESSAGE_ID, SUBJECT_TYPE, SUBJECT_ID)
    REFERENCES BUSLANES.ADMIN_DISCUSSION_MESSAGES (ID, SUBJECT_TYPE, SUBJECT_ID);

DROP INDEX IF EXISTS BUSLANES.GEOMETRY_DISCUSSION_READ_STATE_USER_ID_IDX;

CREATE INDEX IF NOT EXISTS ADMIN_DISCUSSION_READ_STATE_USER_ID_IDX
    ON BUSLANES.ADMIN_DISCUSSION_READ_STATE (USER_ID, SUBJECT_TYPE, SUBJECT_ID);

COMMENT ON TABLE BUSLANES.ADMIN_DISCUSSION_MESSAGES IS
    'Persistent human discussions attached to supported administrator subjects.';
COMMENT ON COLUMN BUSLANES.ADMIN_DISCUSSION_MESSAGES.SUBJECT_TYPE IS
    'Discussion subject discriminator: geometry or osm-boundary.';
COMMENT ON COLUMN BUSLANES.ADMIN_DISCUSSION_MESSAGES.SUBJECT_REVISION IS
    'Subject UPDATED_AT value observed when the message was created.';

COMMENT ON TABLE BUSLANES.ADMIN_DISCUSSION_READ_STATE IS
    'Per-user persistent read position for administrator discussion subjects.';
