SET SEARCH_PATH = BUSLANES, PUBLIC;

-- V063 existed briefly in two equivalent forms:
-- PostgreSQL versions that support a column-list SET NULL action used the
-- composite FK directly, while older supported installations use a trigger.
-- Normalize both histories to one portable representation.

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_READ_STATE
    DROP CONSTRAINT IF EXISTS ADMIN_DISCUSSION_READ_STATE_MESSAGE_FKEY;

CREATE OR REPLACE FUNCTION BUSLANES.CLEAR_ADMIN_DISCUSSION_READ_STATE_MESSAGE()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $admin_discussion_read_state$
BEGIN
    UPDATE BUSLANES.ADMIN_DISCUSSION_READ_STATE
       SET LAST_READ_MESSAGE_ID = NULL
     WHERE LAST_READ_MESSAGE_ID = OLD.ID
       AND SUBJECT_TYPE = OLD.SUBJECT_TYPE
       AND SUBJECT_ID = OLD.SUBJECT_ID;

    RETURN OLD;
END;
$admin_discussion_read_state$;

DROP TRIGGER IF EXISTS ADMIN_DISCUSSION_MESSAGES_CLEAR_READ_STATE
    ON BUSLANES.ADMIN_DISCUSSION_MESSAGES;

CREATE TRIGGER ADMIN_DISCUSSION_MESSAGES_CLEAR_READ_STATE
    BEFORE DELETE ON BUSLANES.ADMIN_DISCUSSION_MESSAGES
    FOR EACH ROW
    EXECUTE FUNCTION BUSLANES.CLEAR_ADMIN_DISCUSSION_READ_STATE_MESSAGE();

ALTER TABLE BUSLANES.ADMIN_DISCUSSION_READ_STATE
    ADD CONSTRAINT ADMIN_DISCUSSION_READ_STATE_MESSAGE_FKEY
    FOREIGN KEY (LAST_READ_MESSAGE_ID, SUBJECT_TYPE, SUBJECT_ID)
    REFERENCES BUSLANES.ADMIN_DISCUSSION_MESSAGES (ID, SUBJECT_TYPE, SUBJECT_ID);
