CREATE TABLE IF NOT EXISTS BUSLANES.ADMIN_IP_ALLOWLIST
(
    ID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NETWORK     CIDR        NOT NULL UNIQUE,
    CREATED_AT  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CREATED_BY  BIGINT      REFERENCES BUSLANES.ADMIN_USERS (ID) ON DELETE SET NULL,
    REASON      TEXT,
    CONSTRAINT ADMIN_IP_ALLOWLIST_REASON_LENGTH CHECK (
        REASON IS NULL OR CHAR_LENGTH(REASON) <= 500
    )
);

CREATE INDEX IF NOT EXISTS ADMIN_IP_ALLOWLIST_NETWORK_GIST_IDX
    ON BUSLANES.ADMIN_IP_ALLOWLIST
    USING GIST (NETWORK inet_ops);

COMMENT ON TABLE BUSLANES.ADMIN_IP_ALLOWLIST IS
    'Trusted administrator IP networks excluded from manual and automatic IP lockout. Supports IPv4/IPv6 CIDR.';
